Refactor todo app with redux
CodeSoom/week4-assignment-1 pull request #10
Opened 2020-06-25 09:34 UTC by naraekn

우선 PR 보내고 마저 하겠습니다 ㅠㅠ..

2020-06-25 11:37 UTC, wholemann requested changes
전체적으로 상당히 잘해주셨네요.

TDD 싸이클에 충실하려고 하신 점이 매우 좋습니다.

다만 Test가 너무 한번에 진행된 점이 있고, 이건 사실 이미 구현할 코드를 알고 있기 때문에

벌어진 일이긴 합니다.

실제론 test 하나 추가하고 구현하고 개선하고 이걸 매우 짧게 반복하게 됩니다.

보통은 describe context it에서 처음부터 context가 등장하진 않아요.

하다 보면 맥락이 좀 바뀐 테스트가 필요하단 걸 발견하고

describe - it 에서 describe - context - it으로 바꿔야 함을 발견하죠.

어쨌든 잘하고 계시니 코멘트 참고하셔서 계속 진행해주세요!

2020-06-25 11:37 UTC, wholemann commented on src/App.test.jsx
> +  fireEvent.click(getByText(/완료/));
```suggestion
  fireEvent.change(getByLabelText(/할 일/), { target: { value } });
  fireEvent.click(getByText(/추가/));

  expect(getByText(value)).not.toBeNull();

  fireEvent.click(getByText(/완료/));
  
  expect(getByText(/완료/)).toBeNull();
```

완료 동작의 의미를 좀 더 드러내봤습니다.

2020-06-25 11:37 UTC, wholemann commented on src/actions.test.js
> +} from './actions';
action creator는 굳이 테스트가 필요하진 않은 듯 하네요.

객체 리턴이 하는 일의 전부라서요ㅎㅎ

2020-06-25 11:37 UTC, wholemann commented on __mocks__/react-redux.js
> +export const useSelector = jest.fn();
```suggestion
export const useDispatch = jest.fn();

export const useSelector = jest.fn();
```

이 부분은 한 줄을 띄어주세요.

2020-06-25 11:37 UTC, wholemann commented on src/reducer.test.js
> +describe('reducer', () => {
이 부분은 너무 한 번에 진행한 느낌이에요.

원래 test는 하나씩 추가하고 해당 test를 통과시킬 수 있게 실제 코드를 구현하는 방향으로 가야 합니다.

한 번에 여러 테스트를 추가하는 건 통제하기 어려운 상황으로 갈 확률이 높아요.

2020-06-25 11:37 UTC, wholemann commented on src/reducer.test.js
> +  context('when action type does not exist', () => {
오 꼼꼼하게 하셨군요.

2020-06-25 11:37 UTC, wholemann commented on src/InputContainer.test.jsx
> +describe('Input', () => {
이 부분도 테스트가 너무 한 번에 진행 됐네요!

2020-06-25 11:37 UTC, wholemann commented on src/InputContainer.jsx
> +export default function InputContainer() {
일단 Green으로 만들었군요. 좋네요!

2020-06-25 15:35 UTC, naraekn commented on src/App.test.jsx
> +  fireEvent.click(getByText(/완료/));
피드백을 보기 직전에 한 새로운 커밋에서는 ```App.test.jsx```를 많이 손봤습니다. 

redux를 사용해서 상태관리를 하도록 바꾸니까, 기존의 ```App.test.jsx```에서 에러가 나더라고요! 그래서, 똑같이 ```useDispatch```, ```useSelector```를 써서 테스트도 바꿔줬습니다. 

1) 바뀐 테스트에서도 완료동작의 의미를 조금더 드러내는 것이 좋을까요?
2) 또, App 테스트에서도 redux 구조를 사용해서 테스트를 하는게 맞는지 피드백 해주시면 좋겠습니다. 제가 코드를 잘못짜서(?) 기존 앱 테스트가 동작을 잘 안 하는건지, App에서도 (바뀐 ```App.test.jsx```처럼) redux 구조를 사용해서 테스트를 해야하는건지 궁금합니다.

2020-06-25 15:36 UTC, naraekn commented on src/actions.test.js
> +} from './actions';
앗 그렇군요ㅎㅎㅎ 제거해서 커밋하겠습니다!

2020-06-25 15:39 UTC, naraekn commented on __mocks__/react-redux.js
> +export const useSelector = jest.fn();
반영 했습니다! :)

2020-06-25 23:07 UTC, wholemann commented on src/App.test.jsx
> +  fireEvent.click(getByText(/완료/));
1. 이정도면 '큰 문제 없이 작동을 보장할 수 있다' 는 본인이 정하면 됩니다.

2. 강의를 보시면 아시겠지만 App.test.jsx도 당연히 변경되어야 합니다.

useSelector에 대한 mockImplementation을 하는 걸 보실 수 있을 겁니다.

자식 중에 useSelector를 사용하는 애들이 있기 때문이죠ㅎㅎ

2020-06-25 23:10 UTC, wholemann approved these changes
굉장히 잘해주셨네요.

현재 reducer에 대한 테스트가 하나 빠진 것 같은데 그 부분만 해결해서

test coverage 100% 만들어서 보내주시고 다음 과제 바로 진행하시면 될 것 같아요.

바로 Merge 해드리겠습니다ㅎㅎ

2020-06-26 09:27 UTC, naraekn commented on src/App.test.jsx
> +  fireEvent.click(getByText(/완료/));
그렇군요 감사합니다!! 👍

2020-06-26 09:58 UTC, naraekn commented
1. ```reducer```에서 ```export``` 를 두번 썼더라고요! (어쩐지 계속 빨간줄이..) 해당부분 수정했습니다
2. reducer test 추가했습니다

* 저 그런데 CI는 왜 통과를 못하는걸까요..😢

2020-06-26 15:03 UTC, naraekn commented
ㅎㅎ...```createStore```를 ```react-redux```에서 import해서 일어나는 문제였습니다 ```redux```에서 import하는걸로 코드를 바꿔서 해결했습니다

2020-06-27 02:53 UTC, wholemann approved these changes
Merge할게요. 고생하셨습니다:)

이번에 훈련하실 걸 바탕으로 과제2도 잘 진행해주세요!

2020-06-27 02:54 UTC, merged