:recycle: Redux로 리팩터링
CodeSoom/week4-assignment-1 pull request #133
Opened 2022-08-23 17:26 UTC by 0-Chan

안녕하세요 트레이너님!

아직 Redux를 완벽히 이해 못한 상태인데요..

일단은 '까만색은 IDE고 흰색은 코드다...' 라는 생각으로 코드를 작성 해보았습니다.

아 그리고 **짧은 질문**이 하나 있습니다ㅎㅎ

store.js 를 작성하다가 `createStore` 가 deprecated 되었으니 `configureStore`를 쓰는 걸 추천한다.
라는 창을 보았는데.. 학습을 위헤서 그대로 가는게 나을까요?

2022-08-24 12:01 UTC, daadaadaah commented
오! 빠른 PR 너무 좋습니다!👍
아샬님 강의 보면서 어떻게 진행하는지 하나하나 커밋해보면서 학습해보세요! 저도 처음에 redux 개념을 이해하는게 어려워서 그림까지 그려보면서 이해했었던 것 같아요!ㅎㅎ상태변경을 한꺼번에 진행하려고 하지마시구! 기능하나하나 작은 단위로 쪼개서 진행해보세요~ 물론 TDD로 진행하시는거 잊지 마시구요!ㅎㅎ다음 PR 기대하고 있을게요!ㅎㅎ


> > createStore 가 deprecated 되었으니 configureStore를 쓰는 걸 추천한다.
> 
> 라는 창을 보았는데.. 학습을 위해서 일단 쓰는게 나을까요?

configureStore로 진행해주세요!

2022-08-24 12:10 UTC, daadaadaah commented on src/App.jsx
> +}
아샬님은 이런 코드를 어디서 관리하셨는지 한번 잘 생각해보세요!ㅎㅎ

2022-08-24 13:34 UTC, daadaadaah commented on src/App.jsx
> +    setState(updateTaskTitle(state, event.target.value));
`dispatch`를 활용해봅시다!ㅎㅎ

2022-08-25 09:59 UTC, 0-Chan commented on src/App.jsx
> +}
앗 넵. 마저 강의를 듣고 actionCreator 들은 모두 `actions.js` 에서 관리 하게 하였습니다!

2022-08-25 10:00 UTC, 0-Chan commented on src/App.jsx
> +    setState(updateTaskTitle(state, event.target.value));
화살표 함수를 이용해 jsx 내에서 `dispatch`를 활용 해봤습니다.ㅎㅎ

2022-08-25 10:01 UTC, 0-Chan commented
> 오! 빠른 PR 너무 좋습니다!+1 아샬님 강의 보면서 어떻게 진행하는지 하나하나 커밋해보면서 학습해보세요! 저도 처음에 redux 개념을 이해하는게 어려워서 그림까지 그려보면서 이해했었던 것 같아요!ㅎㅎ상태변경을 한꺼번에 진행하려고 하지마시구! 기능하나하나 작은 단위로 쪼개서 진행해보세요~ 물론 TDD로 진행하시는거 잊지 마시구요!ㅎㅎ다음 PR 기대하고 있을게요!ㅎㅎ
> 
> >  createStore 가 deprecated 되었으니 configureStore를 쓰는 걸 추천한다.
> > 라는 창을 보았는데.. 학습을 위해서 일단 쓰는게 나을까요?
> 
> configureStore로 진행해주세요!

오옷.. 확실히 그림을 그려가면서 공부 해보니까 이해도가 훨씬 높아지는 기분입니다.ㅎㅎ 꿀팁 감사해용

2022-08-25 13:01 UTC, daadaadaah requested changes
헤헤😋 도움이 되었다니 기분이 너무 좋네용😊
한가지 아쉬운 점은 TDD이 작업이 이루어지지 않을 것 같아요😭
기능을 작은 작업단위로 쪼개서 TDD로 한번 작업해보세요! 작업 내역은 commit 메시지에 드러나게 해주시구요!ㅎㅎ(commit 메시지 이모지 들어간거 너무 귀엽네용😝)

2022-08-25 13:01 UTC, daadaadaah commented on src/App.jsx
> +      onClickDeleteTask={(id) => dispatch(deleteTask(id))}
인라인 함수로 했을 때와 함수로 따로 추출했을 때, 어떤 것이 더 유지보수하기 좋을지에 대해 한번 생각해보세요!

2022-08-25 13:01 UTC, daadaadaah commented on src/store.js
> +}
reduce.js 로 따로 빼서 관리해도 괜찮을 것 같아요!ㅎㅎ

2022-08-28 10:41 UTC, 0-Chan commented on src/App.jsx
> +      onClickDeleteTask={(id) => dispatch(deleteTask(id))}
음.. 유지보수 할 때에는 인라인 함수가 아무래도 좀 불리할 것 같다는 생각이 듭니다.

다시 함수로 추출해서 작성 하겠습니다.

2022-08-28 10:45 UTC, 0-Chan commented on src/store.js
> +}
앗 넵넵 분리하는게 관리에도 편리할 것 같습니다!

2022-08-28 12:56 UTC, daadaadaah requested changes
몇가지 코멘트 남겨드렸습니다!ㅎㅎ이번주도 수고 많으셨어요~👏 주간회고를 통해 한주동안에 무엇을 배웠고 어떤 점이 아쉬웠는지 한번 생각해보는 시간을 가져봅시당!ㅎㅎ

2022-08-28 12:56 UTC, daadaadaah commented on src/reduce.js
> +}
if 문이 반복되고 있어요! 어떻게 하면 if 문을 사용하지 않고 reducer를 구현할 수 있을까요? 🤔

2022-08-28 12:56 UTC, daadaadaah commented on src/App.test.jsx
>  test('App', () => {
맥락 구분을 위해 한줄 띄어줍시당!ㅎㅎ

2022-08-28 12:56 UTC, daadaadaah commented on __mocks__/react-redux.js
> +}));
이 코드와 아래 코드로 했을 때 어떤 차이점이 있을까요? 🤔
```js
export const useSelector = jest.fn();
```

2022-08-29 01:52 UTC, 0-Chan commented on __mocks__/react-redux.js
> +}));
아./..! 제가 모킹 하는 방법에 대해 놓칠 뻔 했네요. 짚어주셔서 감사합니다!!

- 아래 코드로 했을 경우
가짜로 된 함수를 넣었을 뿐, 실행 가능한 상태가 아닙니다.
따라서 실제 테스트 하는 곳에서 `mockImplementation`을 사용하여 함수의 동작을 정의합니다.

그런데 저는 react-redux.js에도 정의를 해두고, `mockImplementation`도 사용하는 바람에 뭔가 애매한 코드 였었네요.

2022-08-29 01:52 UTC, 0-Chan commented on src/App.test.jsx
>  test('App', () => {
넵..! 잘 신경 쓰겠습니다.

2022-08-29 01:53 UTC, 0-Chan commented on src/reduce.js
> +}
1주차 때 사용했던 `object literal` 방식을 사용해 if문을 제거 했습니다.

2022-08-29 05:41 UTC, merged