To-do 리스트 Redux를 사용하여 리팩터링 과제 제출
CodeSoom/week4-assignment-1 pull request #135
Opened 2022-08-27 00:59 UTC by ChoJinmok

## :: 최근 작업 주제
- [x] 기능 추가
- [ ] 리뷰 반영
- [x] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표
- To-do 리스트 Redux를 사용하여 리팩터링
<br />

## :: 구현 사항 설명
- 1차 제출
  - Input test
    - 화면 렌더링 테스트
      - input(placeholder, type), button(text) 체크
    - input에 chage 이벤트 테스트
      - onChange함수 호출 여부, input value가 입력 text로 변경됐는 지 테스트
    - 추가 버튼 click 이벤트 테스트
      - onClick함수 호출 여부, input이 빈 문자열 되는지 체크(진행중)
- 2차 제출 - 리뷰반영
  - BDD 반영중
- 3차 제출
  - Input test 리뷰 반영
  - Item test BDD화
  - List test 작성
    - tasks가 비어있을 때와 값이 있을 때를 context로 나누어서 테스트
  - Page test 작성중
- 4차 제출
  - 리뷰 반영(describe - context - it 맥락 맞추기)
  - App test 작성중
<br />

## :: 기타 질문 및 특이 사항
- ~~Input 컴포넌트에서 추가 버튼을 누르면 input 태그의 값이 사라져야하는데 이것도 테스트하는게 맞나요? 테스트 코드가 처음이다보니 쉽지 않네용 ㅠㅠ~~
- ~~input 값이 사라져야 한다면 로직을 handleClick 함수안에 넣어줘야하는게 맞을까요?~~
- ~~List, Page 같은 컴포넌트들이 모이는 컴포넌트들에서 렌더링 테스트 해줄 때 자식 컴포넌트들의 모든 요소들을 모두 확인 해줘야 할까요?~~

2022-08-27 12:49 UTC, daadaadaah requested changes
처음 PR 날리셨는데, 테스트 코드 작성에 제법 익숙해지신 것 같아서 좋았습니다!👍👍👍
몇가지 코멘트 남겨드렸는데 한번 확인해보세요!

2022-08-27 12:49 UTC, daadaadaah commented on src/Input.test.jsx
> +  const setup = (text = '') => render(
이전 과제에서 setup이라고 쓰셔서 쓰신것 같은뎅, 모든 컴포넌트 렌더 호출을 setup이라고 네이밍하는 것보다 좀더 명확하게 의도를 드러내주는 네이밍(예 : renderInput)이 좋을 것 같아요!ㅎㅎ

2022-08-27 12:49 UTC, daadaadaah commented on src/ListContainer.test.jsx
> +  let dispatch;
let을 사용하지 않고 문제를 해결해보세요!ㅎㅎ

2022-08-27 12:49 UTC, daadaadaah commented on src/ListContainer.test.jsx
> +    ];
tasks 처럼 게 여러 곳에서 사용되는 테스트 데이터를 fixture라고 이야기합니다. fixtures 폴더 하나 만들어서 관련 데이터들을 따로 관리해볼까요?

2022-08-27 12:49 UTC, daadaadaah commented on src/reducer.js
> +  return state;
if 문이 반복되고 있어요! 어떻게 하면 if 문을 사용하지 않고 reducer를 구현할 수 있을까요? 🤔

2022-08-27 12:49 UTC, daadaadaah commented on src/reducer.test.js
> +  context('when recieving unspecified action type', () => {
정의되지 않은 액션 타입을 테스트하고 싶으셨나요?

2022-08-27 12:49 UTC, daadaadaah commented on src/App.test.jsx
> +}
given2 라이브러리를 사용하면 하시면, 이렇게 함수로 안뺴주셔도 될거예요!

2022-08-28 05:19 UTC, ChoJinmok commented on src/Input.test.jsx
> +  const setup = (text = '') => render(
아하!~ 그렇네요?! 공식문서에 setup이라고 돼있어서~ 아무생각없이 사용했는데 반성합니다 😭

2022-08-28 07:27 UTC, ChoJinmok commented on src/ListContainer.test.jsx
> +  let dispatch;
beforeEach에서 정의한 변수를 테스트에서 사용하려면 let밖에 방법이 없다고 생각했었는데, 트레이너님 말씀 듣고 const로 dispatch를 beforeEach 바깥쪽에다 정의 하고 beforeEach에는 useDispatch만 만들어 줬는데 이렇게해도 괜찮을 거 같네요!! 제가 맞게 한 걸까요..?

2022-08-28 07:37 UTC, ChoJinmok commented on src/ListContainer.test.jsx
> +    ];
아~~ㅎㅎ 좋은 리뷰 감사합니다!

2022-08-28 07:52 UTC, ChoJinmok commented on src/reducer.test.js
> +  context('when recieving unspecified action type', () => {
맞습니다!!~ 혹시나 action type이 잘못 들어왔을 때를 테스트 하고 싶었어요!!

2022-08-28 14:00 UTC, daadaadaah commented on src/ListContainer.test.jsx
> +  let dispatch;
beforeEach 가 왜 필요하다고 느끼셨나요?

2022-08-29 05:41 UTC, merged

2022-08-29 08:31 UTC, ChoJinmok commented on src/ListContainer.test.jsx
> +  let dispatch;
useDispatch나 useSelector가 여러 테스트에 사용되는데 그냥 describe안에 선언해주는 것 보다 beforeEach와 afterEach로 정리를 해주면서 사용하는게 좋다고 생각했습니다!

2022-08-30 10:51 UTC, ChoJinmok commented on src/reducer.js
> +  return state;
object liter로 바꿔봤습니다!!ㅎㅎ

2022-08-30 13:39 UTC, ChoJinmok commented on src/App.test.jsx
> +}
오~! 감사합니다! given2 사용하니까 훨씬 간편하네요!!😆