App 컴포넌트 내에서 관심사 분리를 하였습니다.
CodeSoom/week4-assignment-1 pull request #141
Opened 2022-11-02 11:27 UTC by yxxnhx

상태를 관리하는 함수 updateTaskTitle, addTask, deleteTask를 생성하여 App 컴포넌트 외부로 분리시켰습니다.

2022-11-02 14:24 UTC, daadaadaah requested changes
redux 처음 접하시면 어려우실텐대 3일만에 PR 날리신 점 너무 잘하셨어요!👍👍👍  
남겨드림 코멘트 참고해서 과제를 마저 완성시켜 봅시다! 그리고, 의도적으로 TDD 싸이클에 맞춰 코딩해보려고 노력해보세요! 지금 습관을 잘 들여놔야 나중에 자연스럽게 TDD 하실 수 있어요! 작업 단위도 작게 해보시구요!ㅎㅎ그럼 다음 PR 기다리고 있을게요!🚀

> 혹시 리덕스에 대해서 더 참고할 수 있는 사이트가 있다면 추천해주시면 정말 감사하겠습니다!
- 제가 공부했을 떄에는 생활코딩 참고했었어요! 리액트 11기분들도 생활코딩 강의 이해하기 쉽다고 하시더라구요!
- 저는 아래 링크 보면서 직접 손으로 그려보기도 하면서 redux를 맨처음에 이해한 것 같아요! 도움이 되었으면 좋겠습니다😊
참고 : https://www.youtube.com/playlist?list=PLuHgQVnccGMB-iGMgONoRPArZfjRuRNVc

2022-11-02 14:24 UTC, daadaadaah commented on src/reducer.test.js
> +    });
혹시, 이 테스트는 tasks에 존재하지 않는 id일 경우, 아무런 동작을 하지 않는 걸 기대하고 한 테스트인가요?
만약, 그렇다면, 숫자를 정말 존재할 수 없는 `음수`로 값을 넣어줄 것 같아요! ㅎㅎ진짜 존재하지 않는 숫자라는 것을 드러내기 위해서요!

2022-11-02 14:24 UTC, daadaadaah commented on src/reducer.test.js
> +  describe('updateTaskTitle를 실행할 시', () => {
describe는 `테스트 대상`에 대해 것이므로, 그냥 `updateTaskTitle`로 기재해주셔도 됩니다!ㅎㅎ(다른 테스트 코드도 같이 바꿔주세요!)

2022-11-02 14:24 UTC, daadaadaah commented on src/reducer.js
> +  }
우리는 이전 과제들을 하면서 if문이 많을 경우, 어떤 걸 활용해서 코드를 간단히 했습니다!ㅎㅎ한번 적용시켜봅시당!ㅎㅎ

2022-11-02 14:24 UTC, daadaadaah commented on __mocks__/react-redux.js
> +export const useSelector = jest.fn((selector) => selector({}));
아샬님은 useSelector를 어떻게 mocking 하셨는지 강의를 통해 한번 체크해봅시당!ㅎㅎ

2022-11-02 14:24 UTC, daadaadaah commented on src/App.test.jsx
> +import tasks from '../fixtures/tasks';
오! 앞에서 배운대로 바로 `fixtures`를 활용하셨군요! 잘하셨어요👏

2022-11-02 14:25 UTC, daadaadaah commented on src/reducer.js
> +  }
이 코멘트는 무시해주세요! 이미 잘 적용시키셨네용!👏👏👏👏👏👏

2022-11-02 17:10 UTC, yxxnhx commented on src/reducer.test.js
> +    });
아하 막연히 그냥 다른 숫자면 된다고 생각했는데 정말 존재할 수 없는 숫자를 이용하는 편이 훨씬 더 정확하겠네요! 변경하겠습니다~!

2022-11-02 17:10 UTC, yxxnhx commented on src/reducer.test.js
> +  describe('updateTaskTitle를 실행할 시', () => {
넵 전체적으로 수정하겠습니다!

2022-11-02 17:10 UTC, yxxnhx commented on __mocks__/react-redux.js
> +export const useSelector = jest.fn((selector) => selector({}));
앗 더는 기본값이 필요없네요 수정하겠습니다!

2022-11-02 17:16 UTC, yxxnhx commented
안녕하세요 트레이너님!
트레이너님 조언을 참고해서 test의 id가 존재하지 않을 경우의 테스트 조건을 음수로 수정하여 정말 존재하지 않을 수 있도록 변경하였습니다.
그리고 전체적으로 필요없는 말이 들어간 descirbe도 수정하였습니다.
관심사 분리를 위해 ListContainer와 InputContainer를 생성하여 각각의 테스트 케이스를 추가하여 테스트 커버리지 100을 달성하였습니다.
아직 많은 것이 부족해 이것저것 찾아보면서 하고 있는 중입니다💪
트레이너님께서 추천해주신 생활코딩 리덕스 강의를 참고해서 더 해보도록 하겠습니다!
강의 추천해주셔서 감사합니다❤️‍🔥

2022-11-04 06:34 UTC, daadaadaah approved these changes
잘하셨어요!👏 이제 commit를 명령형으로 써보시는건 어떠신가요? `~ 수정했습니다` 보다 보통 `~ 수정` 간단히 적어줍니다!ㅎㅎ과제2도 화이팅해봐요!💪

2022-11-07 04:14 UTC, merged