4주차 과제 - Todo 리스트 Redux를 사용하여 리팩터링 하기
CodeSoom/week4-assignment-1 pull request #142
Opened 2022-11-02 12:36 UTC by sejineeee

안녕하세요.

2022-11-02 14:51 UTC, daadaadaah requested changes
이번 PR에서 가장 칭찬해드리고 싶은 부분은 commit 을 잘게 쪼개서 작업단위로 하신 점이예요! 잘하셨어요!👏👏👏
다만, [18fc425](https://github.com/CodeSoom/react-week4-assignment-1/pull/142/commits/18fc425a7d31b2a19e39832e464ca10673efe671) 이 커밋은 redux 사용 전에 먼저 해주셨으면 더 좋았지않을까 생각해요!ㅎㅎ
다음 PR 기다리고 있겠습니당!😊

2022-11-02 14:51 UTC, daadaadaah commented on __mocks__/react-redux.js
> +);
아샬님은 useSelector를 어떻게 mocking 하셨는지 강의를 통해 한번 체크해봅시당!ㅎㅎ

2022-11-02 14:51 UTC, daadaadaah commented on src/reducer.test.js
> +          deleteTask(100),
혹시, 이 테스트는 tasks에 존재하지 않는 id일 경우, 아무런 동작을 하지 않는 걸 기대하고 한 테스트인가요?
만약, 그렇다면, 숫자를 정말 존재할 수 없는 `음수`로 값을 넣어줄 것 같아요! ㅎㅎ진짜 존재하지 않는 숫자라는 것을 드러내기 위해서요!

2022-11-02 14:51 UTC, daadaadaah commented on src/reducer.js
> +  }
우리는 이전 과제들을 하면서 if문이 많을 경우, 어떤 걸 활용해서 코드를 간단히 했습니다!ㅎㅎ한번 적용시켜봅시당!ㅎㅎ

2022-11-02 14:51 UTC, daadaadaah commented on src/ListContainer.test.jsx
> +    ];
우리는 이전 과제들을 하면서 이런 테스트용 데어터를 무엇이라고 했고, 어떻게 관리했었을까요?ㅎㅎ

2022-11-02 14:51 UTC, daadaadaah commented on src/ListContainer.test.jsx
> +  it('List', () => {
describe-(context)-it 에 있는 테스트 내용을 하나로 합쳤을 때, 자연스러운 문장이 나오는게 좋아요!
지금 작성해주신 대로 한문장을 만들어보면, `ListContainer`는 `List`이다. 라는 문장이 만들어집니다.
이렇게 만들어진 문장을 보면, 이 문장이 무엇을 의미하는지 동료가 파악하기 힘들어요! 한문장이 되도록 it문을 수정하면 어떻게 수정하는게 좋을까요?ㅎㅎ(다른 테스트들도 한번 체크해봅시당!ㅎㅎ)

2022-11-03 12:08 UTC, sejineeee commented
## 내용
안녕하세요!!!
테스트용 데이터를 fixtures 파일로 분리하였습니다! (분명 지난주에 배웠는데 잊어버리다니...🥺 계속 생각하도록 노력하겠습니다!)
coverage가 100% 달성하지 못한 부분을 일단 수정하였습니다.
reducer 파일에서 사용했던 if문은 객체 리터럴을 사용하는 방법으로 수정하였습니다.
reducer 함수에서는 action type을 확인하는 부분을 삼항연산자로 적어보았습니다.
(삼항연산자보다 if문을 사용하는 게 좀 더 명시적이어서 좋을까요?)
일단 다른 부분은 coverage가 100% 달성하였으나, reducer 파일에 action type이 일치하는게 없을 경우 state를 반환하는 부분이 계속 실패합니다. 일단 멘토님에게 질문 남겨놓고, 그 후에도 다시 시도해보겠습니다!

## 질문
<img width="688" alt="스크린샷 2022-11-03 오후 8 58 06" src="https://user-images.githubusercontent.com/86041335/199716333-2ca420be-c162-4e2a-bf23-06cc3af8a7d4.png">

`reducer.test.jsx` 파일에서 action type이 없을 경우 test 부분에서 type을 읽을 수 없다고 하는데, 어떤 식으로 테스트를 접근해야 될 지 잘 모르겠습니다.

2022-11-04 06:50 UTC, daadaadaah requested changes
질문 주신 내용 관련 코드에 코멘트 남겨 놨습니다! 참고하세요😄

2022-11-04 06:50 UTC, daadaadaah commented on src/ListContainer.test.jsx
>      const { getByText } = render(<ListContainer />);
테스트 코드도 리팩터링하는 것이 좋습니다! 중복되는 코드들을 한번 정리해봅시다!ㅎㅎ

2022-11-04 06:50 UTC, daadaadaah commented on src/reducer.js
> +  return reducers[action.type] ? reducers[action.type](state, action) : state;
sejineeee님이 작성해주 신 코드는`reducers[action.type]` 자체가 없을 때이므로, sejinneeee의 의도("reducer 파일에 action type이 일치하는게 없을 경우 state를 반환하는 부분이 계속 실패합니다.")에 맞게 표현된 코드가 아닙니다! if문을 활용해서 `reducers[action.type]` 자체가 없을 때 뿐만 아니라 action type이 없을 때도 함께 고려해서 작성해봅시다!ㅎㅎ

2022-11-04 06:50 UTC, daadaadaah commented on src/reducer.test.js
> +  it('action type이 일치하는 게 없을 경우 현재 상태를 반환한다', () => {
1. 이 테스트로 알고 싶은게, 정의된 액션 타입에 아닌 경우, 현재 상태를 반환하는 걸 테스트 해보고 싶으셨나요? 아니면 action 자체가 없는 걸 테스트 하고 싶으셨나요? 이것도 sejinneee님이 표현하신 테스트 내용과 테스트 코드가 일치하지 않습니다!
2. 만약, 정의된 액션 타입이 아닌 경우에 대해 테스트 해보고 싶으셨다면, reducer에 action 값을 넣어주셔야 됩니다!
```js
  describe('non-exited action type', () => {
    it('happens nothing', () => {
      const prevState = {
        newId: 100,
        taskTitle: '',
        tasks: [],
      };

      const action = {
        type: 'non-exited action type', // 값은 제가 임의로 넣었습니다!
      };

      const newState = reducer(prevState, action);

      expect(newState).toBe(prevState);
    });
  });
```

2022-11-04 08:06 UTC, sejineeee commented on src/reducer.test.js
> +  it('action type이 일치하는 게 없을 경우 현재 상태를 반환한다', () => {
action의 type이 일치하지 않은 경우를 표현하고 싶었습니다!! 처음에 리덕스가 동작될 때, type에 이러한 것이 들어오기 때문에 처리를 action의 type이 일치하지 않은 경우를 처리해주고 싶었습니다!
<img width="659" alt="스크린샷 2022-11-04 오후 4 20 19" src="https://user-images.githubusercontent.com/86041335/199923362-d7da0621-bfca-49a1-a5bc-c57685070a4d.png">

2022-11-04 11:17 UTC, sejineeee commented
## 내용
안녕하세요!! 멘토님의 코멘트 덕분에
-  reducer에서 deleteTask에 task에 존재하지 않는 경우일 때, id를 음수로 변경하였습니다.
- 중복된 코드를 함수로 분리하였습니다.
- action이 없을 경우를 조건문에 추가하였습니다.
- 테스트에 아무런 동작을 하지 않을 경우와 action의 type이 일치하지 않는 경우를 나뉘어 테스트하였습니다.

## 질문
1. reducer에서 조건을 체크해줬을 때, 옵셔널 체이닝을 이용해도 괜찮은가요? 아니면 if문을 사용하는 게 더 괜찮은가요?
```javascript
export default function reducer(state, action) {
  return reducers[action?.type] ? reducers[action.type](state, action) : state;
}
```
2. 코멘트를 참고하여 action의 type이 없는 경우를 체크해주고 싶어서, `action.hasOwnProperty('type')`으로 표현하려고 했는데, eslint에서 사용할 수 없다고 안내를 해주던데, 그 이유가 궁금해요...🤔

3. console을 출력해봤을 때, 아무런 행동을 해주지 않아도 기본적으로 action의 type이 들어와서, 일치하지 않기 때문에 undefined가 나와서 처음에 조건문을 action type만 확인하는 식으로 처리한 것이었는데, 이 부분이 아직 완전히 이해가 잘 되지 않습니다ㅠㅠ

이번 한 주도 감사합니다.

2022-11-05 04:07 UTC, daadaadaah approved these changes
> 1. reducer에서 조건을 체크해줬을 때, 옵셔널 체이닝을 이용해도 괜찮은가요? 아니면 if문을 사용하는 게 더 괜찮은가요?

- 개발자마다 다르겠지만, 저는 좀더 의도를 드러낼 수 있도록 if문을 사용하는게 읽기 편합니다!

> 2. 코멘트를 참고하여 action의 type이 없는 경우를 체크해주고 싶어서, action.hasOwnProperty('type')으로 표현하려고 했는데, eslint에서 사용할 수 없다고 안내를 해주던데, 그 이유가 궁금해요...🤔
- eslint 에서 어떤 메시지를 보여주면서 안된다고 했는지, 같이 보여주시면 좋을 것 같아요!

> 3. console을 출력해봤을 때, 아무런 행동을 해주지 않아도 기본적으로 action의 type이 아래 사진과 같이 들어와서 확인이 되길래, 처음에 조건문을 action type만 확인하는 식으로 처리한 것이었는데, 조건문에 action.type만 확인하면 안되는 것인가요...? 아직 이 부분이 완전하게 이해되지 않아서 궁금합니다!!

- 질문을 정리하자면, action.type만 확인하면 안된다는 의미가 아래 코드처럼 작성하면 안된다는 의미로 이해하면 될까용?
```
reducers[action.type] ? reducers[action.type](state, action) : state;
```

2022-11-05 04:50 UTC, sejineeee commented
제가 처음에 action에서 type을 확인하고자 할 때
![스크린샷 2022-11-05 오후 1 18 42](https://user-images.githubusercontent.com/86041335/200101201-3481aedf-5761-4d02-b059-8217c7c0daf2.png)
이런식으로 eslint 안내가 뜨길래 안내 문구를 찾아서, 
![스크린샷 2022-11-05 오후 1 30 17](https://user-images.githubusercontent.com/86041335/200101640-b12c1adf-ff10-4686-9a20-8499437f2264.png)
이렇게 바꿔서 해결해보았습니다!

세 번째 마지막 질문에서는 test에 대한 것이었어요!! 브라우저에서는 잘 작동했는데, 테스트에서는 계속 action.type을 찾을 수 없다고 했는데, 생각해보니 제가 테스트를 잘못 작성했던 것이었어요! (daadaadaah 멘토님께서 type을 체크해주고 싶을 때의 예시로 작성해주신 코드를 이용하면 되는 것이었더라고요...😯)

이번 한 주도 정말 감사합니다!! 두 번째 과제도 늦게나마 PR 올려보도록 하겠습니다!!!!

2022-11-07 04:14 UTC, merged