To-do 리스트 Redux를 사용하여 리팩터링
CodeSoom/week4-assignment-1 pull request #143
Opened 2022-11-04 11:15 UTC by hyeji07

react-week4-assignment-1
To-do 리스트 Redux를 사용하여 리팩터링

Redux는 아직 익숙하지 않아 어렵네요..ㅠㅠㅜ😥 공부가 더 필요할 것 같습니다..

2022-11-05 03:56 UTC, daadaadaah requested changes
Redux 처음에 많이 어렵죵ㅜㅜ😭 그래도, 처음 PR 날려주셨는데, 잘 과제를 수행하셨어요!👏
아직 익숙하지 않은 거 뿐이니, 너무 걱정하지 마세요! 계속 사용하게 되면, 어느순간 익숙해집니다!ㅎㅎ 
남겨드린 코멘트 참고해서 다음 PR 날려주세요!🚀

2022-11-05 03:56 UTC, daadaadaah commented on src/Input.test.jsx
> +  it('value값이 변경되면 onChange함수가 실행된다 ', () => {
`value 값이 변경되면` 이라는 표현 보다 좀더 의도가 드러나는 표현은 없을까요? `value` 라는 단어는 어느 곳에서 사용될 수 있으므로, 의도가 좀더 드러나는 단어를 사용하는게 더 좋을 것 같아요!ㅎㅎ

2022-11-05 03:56 UTC, daadaadaah commented on src/InputContainer.test.jsx
> +  it('입력한 값으로 할 일이 랜더링된다.', () => {
테스트 코드에 맞게 테스트 내용도 변경해주시는게 좋을 것 같아요!
지금 테스트 코드로 어떤 상황을 테스트하고 있는지 다시 한번 체크해봅시당!👊

2022-11-05 03:56 UTC, daadaadaah commented on src/index.jsx
> +  ), /* Provider를 통해 store를 쓸 수 있도록 내려주면 App에서 사용가능 */
주석은 정리해서 PR 보내주세요~ㅎㅎ

2022-11-05 03:56 UTC, daadaadaah commented on src/reducer.test.js
> +      it('입력한 할 일이 랜더링된다', () => {
`렌더링`이라는 용어는 DOM 과 관련된 곳에서 사용하는 용어입니다. reducer에 맞게 용어를 변경해줍시당!ㅎㅎ

2022-11-05 03:56 UTC, daadaadaah commented on src/reducer.test.js
> +    context('id가 없을 경우', () => {
`id가 있을/없을 경우` 보다 `존재하는 id인 경우, 존재하지 않은 id인 경우`로 표현해주시는게 좀더 적절하지 않을까 하는데, 어떻게 생각하시나요?ㅎㅎ

2022-11-05 03:56 UTC, daadaadaah commented on src/reducer.test.js
> +        }, deleteTask(100));
진짜 존재할 수 없는 id 값을 사용하는게 좀더 의도가 드러날 수 있을 것 같아요! 저라면 `음수`를 활용할 것 같아요!

2022-11-05 03:56 UTC, daadaadaah commented on src/App.test.jsx
> +import tasks from '../fixtures/tasks';
앞에서 배운 `fixture`를 활용하셨군요! 잘하셨어요👏

2022-11-05 13:03 UTC, hyeji07 commented on src/Input.test.jsx
> +  it('value값이 변경되면 onChange함수가 실행된다 ', () => {
"할 일이 변경되면 handleChange함수가 실행된다"로 변경하였습니다!

2022-11-05 13:03 UTC, hyeji07 commented on src/InputContainer.test.jsx
> +  it('입력한 값으로 할 일이 랜더링된다.', () => {
"입력된 값으로 할 일이 변경된다" 로 수정하였습니다

2022-11-05 13:03 UTC, hyeji07 commented on src/reducer.test.js
> +      it('입력한 할 일이 랜더링된다', () => {
'입력한 할 일로 목록이 만들어진다'로 변경하였습니다

2022-11-05 13:04 UTC, hyeji07 commented on src/reducer.test.js
> +    context('id가 없을 경우', () => {
😀적절한것같습니다! 수정하였습니당

2022-11-05 13:12 UTC, hyeji07 commented
늘 감사드립니당..👍 코멘트에 따라 수정하여 커밋하였습니다!

2022-11-06 04:26 UTC, daadaadaah approved these changes
잘하셨어요! 👏 이제 commit도 작은 작업 단위로 관리하는 것을 연습해보시면 좋을 것 같아요!ㅎㅎ

2022-11-06 07:06 UTC, hyeji07 commented
네넵! 감사합니다 😀

2022-11-07 04:14 UTC, merged