Refactor TODO list by redux
CodeSoom/week4-assignment-1 pull request #15
Opened 2020-06-26 15:46 UTC by newoo

회사업무가 바빠 너무 늦었지만, 리뷰 요청합니다.

수고하세요.

2020-06-27 02:01 UTC, hannut91 requested changes
고생하셨습니다 ㅎㅎ TDD를 좀더 연습하시면 좋을 것 같아요. 코드를 구현하기 전에 내가 정말로 원하는 기능이 무엇인가? 를 더 고민해보시고 테스트를 작성하시고 그 것을 통과하도록 연습해보세요. 이태원 코딩도장에서 어떻게 했었나 더 고민해보시면 좋을 것 같아요!

2020-06-27 02:01 UTC, hannut91 commented on src/App.test.jsx
> +  expect(getByText(testTasks[0].title)).not.toBeNull();
`toBeInTheDocument` matcher를 사용하면 좀더 표현력이 좋을거에요.

```js
expect(getByText(testTasks[0].title)).not.toBeInTheDocument();
```

See also
  - https://github.com/testing-library/jest-dom#tobeinthedocument

2020-06-27 02:01 UTC, hannut91 commented on src/InputContainer.test.jsx
> +      const testInputEvent = { target: { value: testTaskTitle } };
이 변수 선언은 사용하는 곳 바로 위에서 선언하는게 좋을 것 같아요

2020-06-27 02:01 UTC, hannut91 commented on src/ListContainer.test.jsx
> +      const emptyTasks = [];
우변의 식이 이미 충분히 empty라는 것을 표현하고 있는 것 같아요. `Inline Variable` 리팩터링을 하면 좋을 것 같아요.

See also
  - https://refactoring.com/catalog/inlineVariable.html

2020-06-27 02:01 UTC, hannut91 commented on src/reducer.js
> +  if (action.type === 'updateTaskTitle') {
`if`나 `switch`없이 이 문제를 해결할 수 있을까요? 이전 과제에서 배웠던 것을 적용해보시면 좋을 것 같아요

2020-06-27 08:28 UTC, newoo commented on src/reducer.js
> +  if (action.type === 'updateTaskTitle') {
Map을 사용한다던지, 삼항연산자 등을 활용해보았는데, 잘 안되네요;; 힌트를 더 주실 수 있을까요?

2020-06-27 09:41 UTC, hannut91 commented on src/reducer.js
> +  if (action.type === 'updateTaskTitle') {
Object를 활용하시면 좋을 것 같습니다 ㅎㅎ

2020-06-27 10:09 UTC, hannut91 commented on src/reducer.js
> +  if (action.type === 'updateTaskTitle') {
`Computed property names`을 사용하시면 될 것 같아요 ㅎㅎ

2020-06-27 10:28 UTC, hannut91 approved these changes
reducer `switch`와 `if`안쓰고 구현만 하면 될 것 같아요 ㅎㅎ 나머지는 다 좋네용

2020-06-27 10:28 UTC, hannut91 commented on src/InputContainer.test.jsx
> +      fireEvent.change(inputBox, testInputEvent);
이 둘은 연관이 있는 것이니 중간에 빈 줄을 삭제하는게 좋을 것 같아요

2020-06-27 10:28 UTC, hannut91 commented on src/reducer.test.js
> +    it("doesn't change anything", () => {
음.. 여기서 Double quote를 쓰고 있는데 안잡히네요 왜그럴까요?

2020-06-28 03:40 UTC, newoo commented on src/reducer.test.js
> +    it("doesn't change anything", () => {
검색해보니 아래와 같은 예외 규칙이 적용된 것이 아닐까 추측해봅니다
https://eslint.org/docs/rules/quotes#avoidescape

2020-06-28 09:23 UTC, newoo commented
Computed property names를 활용해서 리팩토링해봤습니다.
리뷰 및 머지 부탁드려요

2020-06-28 10:14 UTC, hannut91 commented
좋네요! ㅎㅎ 고생하셨습니다

2020-06-28 10:14 UTC, merged