"To-do 리스트 Redux를 사용하여 리팩터링 하기" 제출
CodeSoom/week4-assignment-1 pull request #17
Opened 2020-06-26 18:23 UTC by anpaul0615

mock 을 어떻게 사용해야 맞는건지 고민이 많아져서 조금 늦었습니다.
좋은 의견 부탁드립니다.

2020-06-27 01:54 UTC, hannut91 requested changes
고생하셨습니다 ㅎㅎ TDD를 좀더 연습하시면 좋을 것 같아요. 코드를 구현하기 전에 내가 정말로 원하는 기능이 무엇인가? 를 더 고민해보시고 테스트를 작성하시고 그 것을 통과하도록 연습해보세요.

테스트에서 전반적으로 중복이 많이 보여요. 이 중복을 없애면 테스트를 관리하기 더 좋을 거에요. 테스트라는게 한 번 작성하고 끝나는 것이 아닌 유지보수해야할 코드이기 때문이에요.

2020-06-27 01:54 UTC, hannut91 commented on src/App.test.jsx
>  });
```js
describe('<App />', () => {
  let tasks;

  beforeAll(() => {
    const dispatch = jest.fn();
    useDispatch.mockImplementation(() => dispatch);
  });

  context('with tasks', () => {
      beforeEach(() => {
        tasks = Tasks;
      });

      beforeEach(() => {
        useSelector.mockImplementation((selector) => selector({ tasks }));
      });

      it('display tasks', () => {
         ...
      });
  });

    context('with empty tasks', () => {
      beforeEach(() => {
        tasks = [];
      });

      beforeEach(() => {
        useSelector.mockImplementation((selector) => selector({ tasks }));
      });

      it('display empty message', () => {
         ...
      });
  });
});
```

이렇게 표현해주면 테스트의 GIVEN이 어떻게 다른지 명확하게 보일거에요

2020-06-27 01:54 UTC, hannut91 commented on src/InputContainer.test.jsx
> +  it('input task', () => {
```js
describe('Enter To-do', () => {
  it('calls updated task title action', () => {
    ...
  });
});
```

테스트가 무엇을 테스트하는지 좀 더 명확하게 써주는건 어떨까요?

2020-06-27 01:54 UTC, hannut91 commented on src/index.jsx
> +import RootStore from './stores';
이름에 `Root`가 들어간 이유가 있을까요? `Root`가 아닌 `store`가 존재하나요?

2020-06-27 01:54 UTC, hannut91 commented on src/reducer.js
> +import ActionHandlers from './action/action-handlers';
액션 핸들러라는 이름이 무슨 뜻인지 잘 이해가 안가요. reducer가 원래 역할은 무엇인가요?

2020-06-27 01:54 UTC, hannut91 commented on src/reducer.test.js
> +    it('set initial-state ', () => {
reduer가 `set`하나요?

2020-06-27 01:54 UTC, hannut91 commented on src/reducer.test.js
> +  describe('invalid action', () => {
`invalid`가 무슨 뜻인지 모르겠어요. 단순히 `존재하지 않는` 액션에 대한 테스트를 하고 싶으셨던 거죠?

2020-06-27 04:22 UTC, anpaul0615 commented on src/reducer.js
> +import ActionHandlers from './action/action-handlers';
액션핸들러에 리듀서가 할일을 선언해놓고, 리듀서가 호출될때마다 위 코드처럼 액션핸들러에서 할일을 가져오도록 구현해봤습니다.

리듀서 내부 if 문을 제거해보려고 액션핸들러라는 개념을 사용해봤는데요. 
액션핸들러는 `action.type` 이 `key` 가 되고 리듀서의 실제 동작 함수가 `value` 가 되는 딕셔너리입니다.

2020-06-27 04:23 UTC, anpaul0615 commented on src/reducer.js
> +import ActionHandlers from './action/action-handlers';
지금보니 액션핸들러가 `~/action/action-handler` 에 위치해있는게 조금 어색하네요.

실제 액션핸들러는 리듀서의 행위를 가지고있는 오브젝트니깐, 리듀서와 가까이 있는게 좋을것같습니다.

또 액션핸들러 라는 이름도 조금 안맞는것같기도 하네요.  이름을 `reducerRouter` 정도로 바꾸는게 더 쉽게 읽힐 것 같습니다.

2020-06-27 04:26 UTC, anpaul0615 commented on src/reducer.test.js
> +    it('set initial-state ', () => {
`function reducer(previousState = initialState, action) { ... }` 에서 
`previousState = initialState` 에 대한 부분을 테스트하고싶어서 `set initial-state` 라고 명세했습니다.

혹시  `initialState` 로 초기화하는걸 테스트명세로 표현하기 좋은 내용이 있을까요?

2020-06-27 04:28 UTC, anpaul0615 commented on src/reducer.test.js
> +  describe('invalid action', () => {
듣고보니깐 `undefined` 액션은 그냥 그대로 `undefined` 인것이지, `invalid` 하다고는 볼수없을것같아요.
명세를 `undefined action` 로 고치는게 좋겠어요.

2020-06-27 04:30 UTC, anpaul0615 commented on src/index.jsx
> +import RootStore from './stores';
`~/stores` 라는 파일에서 들고왔기때문에, 여러개의 `store` 가 있을수있다고 생각했습니다.

지금은 `store` 에 대한 별다른 구분이 없기때문에 RootStore 라고 명명했습니다.

2020-06-27 04:31 UTC, anpaul0615 commented on src/index.jsx
> +import RootStore from './stores';
생각해보니깐 redux 는 단일 store 인데 왜 파일명은 `~/stores` 라고 하는건지 잘 모르겠네요.
꼭 여러개의 다른 store 가 있을수있다는 것처럼 보이거든요..ㅎㅎ

2020-06-27 04:32 UTC, anpaul0615 commented on src/index.jsx
> +import RootStore from './stores';
> 꼭 여러개의 다른 store 가 있을수있다는 것처럼 보이거든요..ㅎㅎ

만약 그렇다면 `RootStore` 보다는 `TodoStore` 가 더 적절해보입니다.

2020-06-27 04:34 UTC, anpaul0615 commented on src/InputContainer.test.jsx
> +  it('input task', () => {
저 부분은 `InputContainer` 에서 할일을 입력하겠다는 의미의 명세인데요.
죄송한데 `input task title` 정도 밖에 안떠오르네요.... 

해당 테스트에 대한 명세 예시를 좀 주실수 있으실까요..?

2020-06-27 04:34 UTC, anpaul0615 commented on src/App.test.jsx
>  });
오 고맙습니다.
`beforeEach` 로 중복코드를 분리해보겠습니다.

2020-06-27 09:40 UTC, hannut91 approved these changes
고생하셨어요 ㅎㅎ 충분히 고민하신 흔적이 많이 보이네요.

2020-06-27 09:40 UTC, hannut91 commented on src/InputContainer.test.jsx
> +  it('input task', () => {
`it`는 실제로 어떤 일이 일어나는지에 대해 기술해주는게 좋을 것 같아요.

```js
describe('input task title', () => {
  it('updates task title', () => {
    ...
  });
});
```

이런 식으로요

2020-06-27 09:40 UTC, hannut91 commented on src/reducer.test.js
> +    it('set initial-state ', () => {
```js
describe('reducer', () => {
  context('when previous state is undefined', () => {
    it('uses initial state', () => {
      ...
    });
  });
});
```

2020-06-27 09:40 UTC, hannut91 commented on src/reducer.test.js
> +    it('set initial-state ', () => {
리듀서가 이전 스테이트가 없을 때 초기 스테이트를 사용하다는 것을 더 드러내면 좋을 것 같아요

2020-06-27 09:40 UTC, hannut91 commented on src/reducer.test.js
> +        }
`expect(nextState.tasks).toEqual(previousState.tasks);`라고 해도 되나요? 실행해보지 않아서 모르겠지만 이렇게 되면 좋을 것 같네요

2020-06-27 11:34 UTC, anpaul0615 commented on src/InputContainer.test.jsx
> +  it('input task', () => {
아하~ 잘알겠습니다. 감사해요!

2020-06-28 01:46 UTC, merged

2020-07-02 00:57 UTC, anpaul0615 commented on src/reducer.test.js
> +        }
테스트 결과입니다.

동일 오브젝트 비교 (nextState 가 그대로 반환된 previousState 인 경우) :
```
expect(nextState.tasks).toEqual(previousState.tasks);  // ok
expect(nextState.tasks).toStrictEqual(previousState.tasks);  // ok
expect(nextState.tasks).toBe(previousState.tasks);  // ok
```

값만 같은 오브젝트 비교  :
```
expect([ ...nextState.tasks ]).toEqual(previousState.tasks);  // ok
expect([ ...nextState.tasks ]).toStrictEqual(previousState.tasks);  // ok
expect([ ...nextState.tasks ]).toBe(previousState.tasks);  // fail
```

'toEqual' 는 단순한 값 비교, 'toStrictEqual' 는 엄격한 값 비교, 'toBe' 는 엄격한 객체 비교 
라고 볼수있을것같습니다.