To-do 리스트 리팩터링 하기
CodeSoom/week4-assignment-1 pull request #26
Opened 2020-10-12 12:21 UTC by bbhye1

### **구현 목표 **

-  To-do 리스트를 redux를 이용해서 상태관리 하도록 변경하기
-  reducer들의 테스트 추가하기 

### **구현 조건**

- 모든 기능은 TDD로 구현합니다. 컴포넌트와 reducer에 대한 테스트가 존재해야 합니다. 먼저 테스트를 추가하고 commit 한 뒤 실제 기능을 추가하고 commit합니다. commit 메시지 로그는 아래와 같이 남아야 합니다.
- if는 사용할 수 있어도 else 사용하실 수 없습니다. GuardClauses 방법을 사용해주세요.
- switch는 사용하실 수 없습니다.
- let은 사용하실 수 없습니다. const만을 사용하여 문제를 해결해주세요.
- 함수 이름과 변수 이름에 줄임말은 사용하실 수 없습니다. 길더라도 명확하게 써주세요.
- indent(인덴트, 들여쓰기) depth를 1로 유지해주세요. 예를 들어, for문 안에 if문이 있으면 indent depth는 2입니다. depth를 줄이는 좋은 방법은 함수(또는 메소드)를 분리하면 됩니다.

### **구현 내용**
-TDD로 리덕스를 생성하는 부분부터 구현했습니다.

2020-10-12 16:05 UTC, hannut91 requested changes

2020-10-12 16:05 UTC, hannut91 commented on src/reducer.test.jsx
> +      it("dosen't work", () => {
`task title`없이 액션을 실행하면 `동작하지 않는다`라는 의미가 무엇인지 조금 더 의도를 드러내면 좋을 것 같아요. 
사실 tasks의 길이가 늘어나지 않는걸 표현해주고 싶었던거죠? 혹은 새로운 task가 추가되지 않는다는 걸 더 드러내는건 어떨까요?

2020-10-12 16:05 UTC, hannut91 commented on src/reducer.test.jsx
> +    context('without task title', () => {
`task title이 없이` 라기 보다는 빈 문자열인 것 같아요. `with empty text`는 어떨까요?

2020-10-12 16:05 UTC, hannut91 commented on src/reducer.test.jsx
> +    });
`context`안에 Given을 명시해서 어떤 것이 변하는지 더 명확하게 해주는 것도 좋은 것 같아요
```js
context('with task title', () => {
  const taskTitle = '첫 번째 할 일';

  it('appends task into tasks', () => {'
    const state = reducer(reduceAddTask(taskTitle), action);
  });
});

context('with empty text', () => {
  const taskTitle = '';

  it('appends nothing', () => {
    const state = reducer(reduceAddTask(taskTitle), action);
  });
});
```

2020-10-12 16:05 UTC, hannut91 commented on src/App.test.jsx
> +  expect(getByText(/두번째 할 일/)).not.toBeNull();
`첫 번째 할 일`과 `두 번째 할 일은 Magic literal인 것 같아요.
`tasks`로 표현해줄 수 있을까요? 스터디 때 배운 Side effect를 일으키고, 모든 항목을 순회한다는 의도를 드러낼 수 있는 `forEach`를 쓰면 좋을 것 같네요

See also
  - https://refactoring.com/catalog/replaceMagicLiteral.html

2020-10-12 16:05 UTC, hannut91 commented on src/actions.js
> +}
`taskTitle`대신에 `title`로 사용하는건 어떨까요? 그러면 좀 더 단순해질 것 같아요

```js
export function updateTaskTitle(title) {
  return {
    type: 'updateTaskTitle',
    payload: { title },
  };
}
```

그런데 밑에서보니 또 title에서 taskTitle로 저장하네요. 일관성있게 통일시켜주는게 좋을 것 같아요

2020-10-12 16:05 UTC, hannut91 commented on src/reducer.test.jsx
> +    });
계속 1이라는게 반복되고 있어요. 이정도 간단한 테스트코드에서는 사실 다 자세히 보면 파악이 가능하긴한데, 복잡한 테스트의 경우 왜 1인지 2가 아니면 안되는지 파악하기 어려울 것 같아요.


```js
describe('deleteTask', () => {
  const id = 1;
  const tasks = [
    { id, title: '첫번째 할 일' },
  ];

  it('remove task from tasks', () => {
    const state = reducer({ tasks }, deleteTask(id));

    expect(stats.tasks).toBeEmpty();
  });
});
```

음.. 이건 너무 복잡해보일까요? `tasks`의 `id`가 `id`라는 걸 파악하기 어려울까요? 아니면

```js
describe('deleteTask', () => {
  const tasks = [
    { id: 1, title: '첫번째 할 일' },
  ];

  it('remove task from tasks', () => {
    const state = reducer({ tasks }, deleteTask(tasks[0].id));

    expect(stats.tasks).toBeEmpty();
  });
});
```

이건 어떨까요

2020-10-13 13:05 UTC, bbhye1 commented on src/reducer.test.jsx
> +    });
마지막   expect(state.tasks).toHaveLength(1); 이 부분만 남기고 수정해 주었습니다. 왠지 만약 하나 눌렀을 때 모두 지워지는 문제가 생겨서 찾아야 한다면 이 부분이 필요할 것같아서요 ㅎㅎ

2020-10-13 13:06 UTC, bbhye1 commented on src/App.test.jsx
> +  expect(getByText(/두번째 할 일/)).not.toBeNull();
이부분은 앞으로 항상 잘 염두하겠습니다!

2020-10-13 13:26 UTC, bbhye1 commented
어제 작성했던 커밋들이 너무 각각의 의도가 안드러나는 커밋메세지로 작성되었던것 같아서 오늘은 조금 더 세세한 메세지로 작성하려고 했습니다. 그렇게 자잘하게 나누어 작성했다고 생각하지 않았는데 커밋수가 많아서 놀랐습니다;;; 이렇게 더 많아지면 많아질수록 커밋메세지의 중요성이 높아질것같아 앞으로 더 신경쓰고 작성해야할 듯 합니다.  

 작성하고 난 후에 각 컴포넌트의 테스트와 Container가 겹치는 부분이 있다고 생각이 되어 중복을 또 제거해줘야 되나 했는데 계속 보다보니 중복이 아니고 각각 테스트하는 방향이 다르다는 걸 느꼈습니다. 각 컴포넌트는 이벤트 실행시 함수가 호출이 되나 안되나가 테스트의 목적이라면 Container에서는 이벤트 실행시 dispatch로 action이 잘 전달되나 안되나가 테스트의 목적인 거라고 생각해서 컴포넌트의 함수호출 부분을 삭제하지 않았습니다.

 뭔가 코드를 많이 작성하면 작성할수록 처음 모든 코드를 다 작성하고 나면 뭐가 부족한지 어디를 실수했는지 한 번에 다 안보이는 느낌이 듭니다. 내일 한번 더 천천히 보면서 오류가 있는지 살펴볼 예정입니다. :)

그리고 과제를 하다가 문득 궁금해진 점이 있습니다. 왜 reducer에서도 if로만 작성을 해야할까요?? 지금 작성하는것은 switch문과 거의 동일한 구조의 if문으로 작성이 되고 있고 검색해서 조금씩 얻은 정보로는switch문이 더 속도가 빠르다고 하는데 그러면 switch문으로 작성하는 것이 좋지 않을까 하는 생각을 했습니다.

2020-10-13 13:36 UTC, hannut91 requested changes

2020-10-13 13:36 UTC, hannut91 commented on src/App.test.jsx
> +  });
```js
const { container, getByText } = render((
  <App />
));

tasks.forEach(({ title }) => {
  expect(container).toHaveTextContent(title);
});
```

텍스트가 있는지 확인할 때는 간단하게 이렇게 할 수도 있을 것 같아요.

See also
  - https://github.com/testing-library/jest-dom#tohavetextcontent

2020-10-13 13:36 UTC, hannut91 commented on src/InputContainer.test.jsx
> +  useDispatch.mockImplementation(() => dispatch);
`const dispatch`변수를 선언한 곳과 사용하는과 거리가 먼 것 같아요. 관련이 있는 것들끼리는 가까이에 같이 모여있는건 어떨까요?

2020-10-13 13:36 UTC, hannut91 commented on src/InputContainer.test.jsx
> +  expect(dispatch).toBeCalledWith(updateTaskTitle(newTaskTitle));
두 가지 테스트가 하나의 테스트 묶음에 같이 있는 것 같아요. 하나의 테스트는 하나의 역할만 하도록 하는건 어떨까요?

2020-10-13 13:36 UTC, hannut91 commented on src/InputContainer.test.jsx
> +  expect(getByDisplayValue(taskTitle)).not.toBeNull();
`getByLabelText`를 이용해서 `input`을 가져오는 건 어떨까요? 그러면 taskTitle을 사용하지 않아도 되고, newTaskTitle도 이름을 taskTitle이나 다른 이름을 사용할 수 있을거에요.

2020-10-13 13:36 UTC, hannut91 commented on src/ListContainer.jsx
> +      onClickDelete={handleClickDeleteTask}
`onClickComplete`는 어떨까요? 만약 삭제하는 대신, 완료 목록에 넣기로 한다면 이름이 조금 모호할 수 있을 것 같아요

2020-10-13 13:36 UTC, hannut91 commented on src/reducer.js
> +  return state;
`if`나 switch문 없이 이걸 구현할 수 있을까요?

2020-10-13 13:36 UTC, hannut91 commented on src/reducer.test.jsx
> +  });
정의되어 있지 않은 action이 주어졌을 때를 테스트하고 싶으셨던 거죠/

2020-10-13 13:36 UTC, hannut91 commented on src/reducer.test.jsx
> +      expect(state.taskTitle).toBe('New title');
여기도 Magic Literal이 사용됐네요

2020-10-13 13:36 UTC, hannut91 commented on src/reducer.test.jsx
> +    }
Arrow 함수를 사용하면 어떤 장점이 있었다고 했었죠?
그리고 얘가 반환하는 것이 `state`인거죠?

2020-10-13 13:36 UTC, hannut91 commented on src/reducer.test.jsx
> +    });
`const taskTitle = '첫번째 할 일';`이게 중복되고 있고, 
이 변수가 테스트에 큰 영향을 주지 않는다면 테스트를 하는 곳 바깥으로 빼도 괜찮을 것 같아요.

무언가가 반복된다면 리팩터링을 해야하는 신호로 보시면 좋을 것 같아요

```js
context('with task title', () => {
  const taskTitle = '첫번째 할 일';
  
  it('appends task into tasks', () => {
  });
});

```

2020-10-13 13:36 UTC, hannut91 commented on src/reducer.test.jsx
> +        expect(state.tasks[0].title).toBe('첫번째 할 일');
여기도 Magic literal대신에 사용한 변수를 사용하는게 좋을 것 같아요

2020-10-13 13:36 UTC, hannut91 commented on src/reducer.test.jsx
> +      expect(state.tasks).toHaveLength(1);
`expect(state.tasks).toHaveLength(tasks.length - 1);`

이건 어떨까요? 어떤 장점이 있을까요?

2020-10-14 07:49 UTC, bbhye1 commented on src/reducer.test.jsx
> +    }
음;;;; 이 부분에서 Arrow함수를 왜 언급하신지 이해를 못하겠어요. 얘가 반환하는 것은 state가 맞는데 강의처럼 reducer를 함수안에 넣어주는게 맞는것 같아 일단 그렇게 수정해주었습니다!

2020-10-14 07:49 UTC, bbhye1 commented on src/reducer.test.jsx
> +      expect(state.tasks).toHaveLength(1);
확실히 하나가 제거된다는걸 명시적으로 표현해주네요!!

2020-10-14 16:57 UTC, hannut91 requested changes

2020-10-14 16:57 UTC, hannut91 commented on src/App.test.jsx
> +  });
구조 분해 할당을 이용해서 이렇게 표현하는 건 어떨까요?

```suggestion
  tasks.forEach(({ title }) => {
    expect(container).toHaveTextContent(title);
  });
```

2020-10-14 16:57 UTC, hannut91 commented on src/Input.test.jsx
>    const handleClick = jest.fn();
mocking함수는 초기화를 해주지 않으면 의도치 않게 동작할 수 있습니다. 예를들어 테스트 A, B가 있는데, A에서 `handleChange`를 실행해버리면 실행된 상태가 그대로 남아 있기 때문에 B에서 `handleChange`실행하지 않았더라도 확인해보면 실행되었다고 결과가 출력됩니다. 따라서 항상 초기화를 해주는게 좋습니다.

```js
beforeEach(() => {
  jest.clearAllMocks();
});
```

See also
  - https://jestjs.io/docs/en/setup-teardown
  - https://jestjs.io/docs/en/jest-object

2020-10-14 16:57 UTC, hannut91 commented on src/Input.test.jsx
> +  it('renders "추가" button', () => {
`추가`라는 말은 구체적인 구현에 의존하기 때문에 더 추상적인 이름이 좋을 것 같아요. 
만약 추가 대신에 `+`아이콘을 사용하기만 해도 이 테스트의 이름은 다시 수정해야 될 것 같아요

2020-10-14 16:57 UTC, hannut91 commented on src/InputContainer.test.jsx
> +  useDispatch.mockImplementation(() => dispatch);
초기화하는 로직은 여기에 바로 쓰기 보다는 `beforeEach`안에서 작성하는게 좋을 것 같아요. 왜냐하면 테스트를 실행할 때 마다 항상 새로운 상태에서 시작해야되기 때문이에요. 이러면 테스트가 다른 테스트에 영향을 주게 됩니다. 그러면 테스트를 유지보수하기 굉장히 어려워질거에요. 철저하게 분리해야 합니다.

2020-10-14 16:57 UTC, hannut91 commented on src/InputContainer.test.jsx
> +  it('dispatch updateTaskTitle action', () => {
테스트대상이 무엇인지 모르겠어요. Input 컨테이너가 `updateTaskTitle` 액션을 dispatch한다는 일만 명시되어있고 실제로 무엇을 테스트하는건지 잘 모르겠어요.

```js
describe('InputContainer', () => {
  describe('change taskTitle', () => {
    it('dispatches updateTaskTitle action', () => {
      ...
    });
  });
});
```

2020-10-14 16:57 UTC, hannut91 commented on src/reducer.js
> +  return { ...state, ...actions[action.type] };
상태에 액션이 들어가있는 것 같아요. 그리고 액션이 아니라 상태를 변경하는 함수는 `reducer`라고 불러요.

2020-10-16 00:58 UTC, hannut91 approved these changes
다 좋습니다 ㅎㅎ

2020-10-16 00:58 UTC, hannut91 commented on src/reducer.js
> +  if (!reducers[action.type]) return state;
한 줄 이더라도 중괄호를 써주는게 더 좋을 것 같아요. 팀의 컨벤션이나 eslint rule에 따라 다르긴 하지만, 한 줄 이더라도 중괄호를 넣자는 파와 그냥 간단하게 쓰자는 파로 나뉩니다.
저는 무조건 써주는걸 선호하긴합니다.

See also
  - https://eslint.org/docs/rules/curly

2020-10-17 02:45 UTC, merged