[Week4][Davidyang2149] Refactor To-do App by Redux - 구현 진행 중
CodeSoom/week4-assignment-1 pull request #28
Opened 2020-10-12 12:54 UTC by DavidYang2149

# 3강 테스트 - 3주 차 과제 1
## 기능 구현
- [ ] 상태 관리를 Redux로 변경해도 모든 컴포넌트 테스트가 통과해야 합니다. 추가로 reducer들에 대한 테스트를 추가해 주세요.

## 제한 조건
- [ ] 모든 기능은 TDD로 구현합니다. 컴포넌트와 reducer에 대한 테스트가 존재해야 합니다. 먼저 테스트를 추가하고 commit 한 뒤 실제 기능을 추가하고 commit합니다. commit 메시지 로그는 아래와 같이 남아야 합니다.
```sh
Restaurant에 대한 테스트를 추가한다
Restaurant을 구현한다
Restaurant를 리팩토링한다
```
- [ ] if는 사용할 수 있어도 else 사용하실 수 없습니다. GuardClauses 방법을 사용해주세요.
- [ ] switch는 사용하실 수 없습니다.
- [ ] let은 사용하실 수 없습니다. const만을 사용하여 문제를 해결해주세요.
- [ ] 함수 이름과 변수 이름에 줄임말은 사용하실 수 없습니다. 길더라도 명확하게 써주세요.
- [ ] indent(인덴트, 들여쓰기) depth를 1로 유지해주세요. 예를 들어, for문 안에 if문이 있으면 indent depth는 2입니다. depth를 줄이는 좋은 방법은 함수(또는 메소드)를 분리하면 됩니다.

## 요구사항
- [ ] ESLint를 돌린 결과 아무런 문제가 없어야 합니다.
- [ ] 모든 인수 테스트를 통과시켜야 합니다.
- [ ] 한 파일에는 하나의 컴포넌트만 있어야 합니다.
- [ ] 테스트 커버리지 100%를 달성해야 합니다.

## 작업내용 및 질의
- [ ] 구현 작업 진행 중

2020-10-13 14:05 UTC, Kihyun92 commented
혹시 잘 안되는 부분이 있다면 언제든 말씀해주셔요~ :)

2020-10-14 15:19 UTC, Kihyun92 requested changes
좋습니다~ 강의의 설명에 맞게 코드를 다뤄보는 것도 좋지만, 더 리펙토링 할 순 없는지 고민하면서 해보시면 더 기억에 남을 것 같습니다~

2020-10-14 15:19 UTC, Kihyun92 commented on src/index.jsx
> +  ),
```suggestion
    <Provider store={store}>
      <App />
    </Provider>,
```
괄호 없이 작성해도 될 것 같아요~

2020-10-14 15:19 UTC, Kihyun92 commented on src/reducer.js
> +  }
`if`문을 쓰지 않고 작성할 방법이 있을까요?? 🤔

2020-10-14 15:19 UTC, Kihyun92 commented on src/reducer.test.js
> +      it('doesn\'t work', () => {
`with` <-> `without`으로 서로 대비되는 테스트임을 나타내는 것도 좋지만, 조금 더 이 테스트에 대해 명확하게 표현해줘도 좋을 것 같아요~

2020-10-14 15:19 UTC, Kihyun92 commented on src/reducer.test.js
> +      it('remove a task from tasks', () => {
마찬가지로 context내의 문장이 `with no existed task ID` 혹은 `with not existed task ID`와 같다면 어떤가요? 그리고 it 내의 문장 또한 해당 테스트를 조금 더 명확히 나타내게 할 수 없을까요?

2020-10-15 13:20 UTC, DavidYang2149 commented on src/index.jsx
> +  ),
바로 이해가 되지 않아 구현단계에서는 강의를 따라하는 것에 초점을 두었습니다.
구현 완료 후 리팩토링에 들어가도록 하겠습니다!

2020-10-15 14:27 UTC, DavidYang2149 commented on src/reducer.test.js
> +      it('remove a task from tasks', () => {
생각해보니 task ID 가 존재하면 remove 작업도 진행되지 않기 때문에 dosen't work 문구를 추가했습니다!

2020-10-15 14:27 UTC, DavidYang2149 commented on src/reducer.test.js
> +      it('doesn\'t work', () => {
no나 not을 적용하는 것으로 수정해보았습니다.

2020-10-15 14:29 UTC, DavidYang2149 commented
@Kihyun92 
현재 reducer.test.js 테스트에서 누락된 coverage를 추가 중인데 누락된 케이스가 어떤건지 감을 잡기가 어렵습니다.
reducer.js 의 7번 째 줄이라고 명시되어 있는데, reducer 함수가 정의되는 케이스였습니다.
도움을 요청드립니다!

2020-10-15 14:44 UTC, DavidYang2149 commented on src/reducer.js
> +  }
object를 이용하면 가능할 것 같은데, 좀 더 고민해보겠습니다!

2020-10-15 15:22 UTC, Kihyun92 commented on src/reducer.js
> +  }
여러 방법이 있겠지만, [Object Literal lookups](https://ultimatecourses.com/blog/deprecating-the-switch-statement-for-object-literals) 을 참고해보셔도 좋을 것 같아요~ 물론 다른 방법도 좋구요 :)

2020-10-15 15:55 UTC, Kihyun92 requested changes
음 터미널에 출력되는 로그를 확인해봐야하겠지만, `reducer.js`에서 `action`이 없는 경우에 대한 처리가 되어있나요?

2020-10-15 15:55 UTC, Kihyun92 commented on src/reducer.test.js
> +    });
`none of all`이라는 문장은 이 테스트를 설명하는데 충분하지 않은 것 같아요! 조금 더 명확히 의도를 드러내도록 수정해보면 좋겠습니다.

그리고 부족한 coverage는 이 테스트가 이유일 것 같습니다. `type`만 세팅되어있는 것 같은데, `payload` 정보도 넘겨줘야 하지 않을까요?

그리고 이렇게까지 복잡하게 하지 않으려면 어떻게 하면 좋을까요? 한번 고민해보시면 좋을 것 같아요 :)

2020-10-16 13:58 UTC, DavidYang2149 commented on src/reducer.test.js
> +    });
말씀해주신 내용을 토대로 수정하였습니다. 감사합니다!

2020-10-16 17:27 UTC, Kihyun92 approved these changes
좋습니다! 과제 2로 빠르게 넘어갑시다~ 👍

2020-10-19 13:30 UTC, merged