[4주차] To-do 리스트 Redux를 사용하여 리팩터링 하기
CodeSoom/week4-assignment-1 pull request #30
Opened 2020-10-12 16:11 UTC by oceanide2

- Redux에 대한 기초 지식이 없어서 Todo App를 redux로 바로 리팩토링을 하지는 못할 것 같습니다. 과제 1은 redux에 최대한 익숙해지기 위해서 아샬님의 동영상 강의 내용을 그대로 따라서 진행해보려고 합니다. 과제 진행 방향을 잘못 생각하고 있다면 어떤 식으로 진행하면 좋을지 조언을 부탁 드립니다.

2020-10-13 14:44 UTC, Kihyun92 reviewed
저희의 의도에 맞게 잘 진행하고 계신 것 같아요!👍잘 하고 계시겠지만, 단순히 강의를 듣고 따라하기만 하는 것보다 아샬님은 어떻게 생각하며 개발하는지 그리고 우리가 `redux`를 사용하는 하는 목적이 뭔지에 집중하시면 더 좋을 것 같아요~ 
그리고 스스로 직접 해보시며 커밋 단위를 잘 쪼개보셔도 좋을 것 같습니다 :)

2020-10-14 15:33 UTC, Kihyun92 requested changes
좋습니다! 강의를 보시고 따라해보는 것도 좋지만, 다 따라하고 보지 않고 스스로 작성해보며 더 좋게 리펙토링해보면 더 기억에 남을 것 같네요~

![image](https://user-images.githubusercontent.com/35797540/96011542-ffc91080-0e7d-11eb-8bbf-96e3e32ad4da.png)

2020-10-14 15:33 UTC, Kihyun92 commented on src/App.test.jsx
> +
`useSelector` 함수에 대해 `mockImplementation`을 왜 해주는 걸까요?
tasks에 대해서도 테스트 해주면 좋을 것 같네요~

2020-10-14 15:33 UTC, Kihyun92 commented on src/index.jsx
> +  ),
```suggestion
    <Provider store={store}>
      <App />
    </Provider>,
```
이렇게 작성해도 괜찮을 것 같네요~

2020-10-14 15:33 UTC, Kihyun92 commented on src/store.js
> +}
reducer내에서 `if`를 쓰지 않고 작성할 방법이 있을까요~?

2020-10-15 00:29 UTC, oceanide2 commented
> 좋습니다! 강의를 보시고 따라해보는 것도 좋지만, 다 따라하고 보지 않고 스스로 작성해보며 더 좋게 리펙토링해보면 더 기억에 남을 것 같네요~
> 
> ![image](https://user-images.githubusercontent.com/35797540/96011542-ffc91080-0e7d-11eb-8bbf-96e3e32ad4da.png)

2020-10-15 00:31 UTC, oceanide2 commented
Redux를 처음 접해서 아직 익숙하지가 않습니다. 우선 강의에 나온대로 진행하면 익숙해지는 것을 먼저 해보려고 합니다. 조언 주신대로 다 따라해보고 보지 않고 다시 한번 해보려고 합니다.

2020-10-15 13:59 UTC, oceanide2 commented
- useDispatch, useSelector를 mock으로 사용하는 것이 아직 정확하게 이해가 되지는 않습니다. 
- TDD 구현 순서로 커밋이 작성되지는 못했고, redux에 익숙해지는 것에 초점이 맞추어 진행하였습니다.

2020-10-15 15:19 UTC, Kihyun92 approved these changes
강의를 안보고 직접 해보신 것 같네요! 좋습니다 👍

>useDispatch, useSelector를 mock으로 사용하는 것이 아직 정확하게 이해가 되지는 않습니다.

우리가 함수 mocking을 왜 하는지 한번 고민해보시면 좋을 것 같아요! mocking 함으로써 우리에게 어떤 장점이 있을까요?

흐름을 보기 좋은 블로그가 있는 것 같아서 공유드려요!
- https://www.daleseo.com/jest-mock-modules/

2020-10-19 13:34 UTC, merged