🎨 Refactoring To-do App Redux
CodeSoom/week4-assignment-1 pull request #31
Opened 2020-10-13 01:39 UTC by Knoa0405

아샬님 코드를 보고 따라해봤습니다. 
다시 초기 상태로 돌린 뒤에 처음부터 혼자 다시 해보겠습니다!

2020-10-13 13:41 UTC, hannut91 reviewed
따라하는 것도 도움이 많이 됩니다 ㅎㅎ 근데 안보고 따라하면 도움이 더 됩니다 ㅎㅎㅎ 배웠던 것을 상기해보면서 과제를 진행해보시면 좋을 것 같아요

2020-10-13 13:41 UTC, hannut91 commented on src/reducer.js
> +}
`if`나 `switch`문 없이 이 문제를 해결할 수 있을까요?

2020-10-13 13:41 UTC, hannut91 commented on src/reducer.test.js
> +    context('without existed task ID', () => {
with not existed task ID는 어떨까요?

2020-10-14 13:11 UTC, Knoa0405 commented
혼자서 처음부터 끝까지 해봤습니다. 확실히 혼자 작성하는 게 어렵네요
아샬님 코드를 그 전에 보고 시작해서인지 아샬님 코드와 비슷하게 작성된 것 같습니다. 추가로 내일까지 coverage 100 % 해서 PR 보내겠습니다~!

2020-10-14 15:08 UTC, Knoa0405 commented
![image](https://user-images.githubusercontent.com/60169820/96008080-25ecb180-0e7a-11eb-880e-12dcb52dd533.png)

>**stackoverflow 검색 결과입니다~!** 
Conditional statements create branches of code which may not be executed (e.g. if/else). This metric tells you how many of your branches have been executed.


> 조건문은 실행할 수 없는 코드 분기를 만든다


혹시 조건문이 조금이라도 있으면 브랜치 coverage 가 안 채워지는 걸까요?
아무리 생각해도 다 했다고 생각했는데 reducer.js 만 조금 모자르네요ㅎㅎ

2020-10-14 16:22 UTC, hannut91 commented
분기문에서 아마 테스트가 안된 항목이 있을거에요 ㅎㅎ 자세한 커버리지 테스트 결과를 보고싶으시다면 `coverage/lcov-report/index.html`을 파일을 열어서 확인해보시면 좋을 것 같습니다

2020-10-14 16:30 UTC, hannut91 requested changes

2020-10-14 16:30 UTC, hannut91 commented on src/InputContainer.test.jsx
> +  it('change title return update dispatch function to be called', () => {
테스트 함수 이름이 좋네요 ㅎㅎ 

```js
describe('change title', () => {
  it('calls update dispatch', () => {
    ...
  });
});
```

이건 어떨까요? 그러면 `discribe-it`을 순서대로 읽으면 `change title calls update dispatch`가 됩니다. `describe`안에 명시하는 것은 테스트하는 실제 대상이고 `it`안에 텍스트들은 실제로 어떤 변화가 일어나는지 기술합니다

2020-10-14 16:30 UTC, hannut91 commented on src/reducer.js
> +}
`if`문이나 `switch`문 없이 이 문제를 해결할 수 있을까요?

2020-10-14 16:30 UTC, hannut91 commented on src/reducer.js
> +};
action이라기 보다는 reducer에 더 가까운 것 같아요. 상태를 변경해주는 일을 하는 함수를 `reducer`라고 부릅니다.

2020-10-14 16:30 UTC, hannut91 commented on src/reducer.test.js
> +  describe('Unhandled action type', () => {
reducer가 정의되어 있지 않은 action type으로 실행되면 초기 상태를 반환한다고 하신 것 같아요
`context`를 이용해서 `Given`을 표현해줄 수 있습니다. 

```js
context('with unhandled action type', () => {
  it('returns initial state', () => {
  });
});
```

2020-10-17 03:58 UTC, hannut91 requested changes

2020-10-17 03:58 UTC, hannut91 commented on src/InputContainer.test.jsx
> +  }));
`beforeEach`함수를 사용해서 테스트가 실행될 때마다 항상 일정한 상태에서 시작할 수 있도록 해주는게 좋을 것 같아요.
그러지 않으면 테스트가 다른 테스트들에 영향을 미칠 수 있고, 그러면 테스트가 올바르게 동작하지 않거나 유지보수하기 힘들어질 거에요.

```js
beforeEach(() => {
useDispatch.mockImplementation(() => dispatch);

useSelector.mockImplementation((selector) => selector({
  taskTitle: 'New Title',
}));
});
```

2020-10-17 03:58 UTC, hannut91 commented on src/reducer.js
> +const reducerChangeStates = {
`reducer`가 상태를 변경하는 함수를 나타내기 때문에 `reducers`라고 해도 충분할 것 같아요

2020-10-17 03:58 UTC, hannut91 commented on src/reducer.js
> +  }
이건 여기서 처리할 것 이 아니라 `addTask`에서 처리해주는게 좋을 것 같아요

2020-10-17 09:58 UTC, Knoa0405 commented on src/InputContainer.test.jsx
> +  }));
넵 수정하겠습니다~!

2020-10-17 10:06 UTC, Knoa0405 commented on src/InputContainer.test.jsx
> +  }));
clearAllmock() 도 가능한 모든 테스트에 beforeEach 로 setup 해두는게 좋을까요?

2020-10-17 10:08 UTC, Knoa0405 commented on src/reducer.js
> +  }
그렇네요  reducers는 객체를 바로 반환하는 구조다 보니 생각을 못했던 것 같습니다.

2020-10-17 14:56 UTC, hannut91 commented on src/InputContainer.test.jsx
> +  }));
mock함수를 사용하면 setup하는게 좋을 것 같아요

2020-10-17 15:31 UTC, hannut91 approved these changes

2020-10-17 15:31 UTC, hannut91 commented on src/InputContainer.test.jsx
> +  beforeEach(() => jest.clearAllMocks());
Arrow 함수는 본문이 한 줄 일 경우에는 return을 생략할 수 있고 본문의 결과가 함수의 결과로 반환합니다. 예를들어

```js
function sum(a, b) {
  return a + b;
}

const sum = (a, b) => a + b;
```

위와 같이 작성할 수 있습니다. 그러면 return을 생략할 수 있고 코드의 길이도 줄어들어서 좋은 점도 있습니다. 하지만 아무런 반환하지 않아야 하는 함수에서 단순히 라인을 줄이기 위해서 Arrow 함수를 사용한다면 잘못된 의도를 전달할 수 있습니다. 따라서 반환값이 없는 함수는 반환값이 없다는 것을 명시적으로 작성해야 합니다.

```js
// 나쁜 예
const handleClick = (value) => setState(value);

// 좋은 예
const handleClick = (value) => {
  setState(value);
}
```

2020-10-17 15:31 UTC, hannut91 commented on src/InputContainer.test.jsx
> +      fireEvent.click(getByText(/추가/));
`getByText`가 중복되고 있는 것 같아요. 코드가 중복이 발생하면 리팩터링해야 될 신호로 보시면 좋습니다.

```js
const addButton = getByText(/추가/);

expect(addButton).not.toBeNull();

fireEvent.click(addButton);
```

2020-10-17 15:31 UTC, hannut91 commented on src/reducer.js
> +  },
우리가 원하는 것은 taskTitle을  이용해서 tasks 목록에 추가하는거고, taskTitle이 있을 때만 실행해야 됩니다. 우리가 원하는 조건이 아닌 경우는 거르고, 조건이 충족할 때만 무언가를 실행한다면 이렇게 해도 좋을 것 같아요

```js
addTask: (state) => {
  const { taskTitle: title, newId, tasks, } = state;

  if (!title) {
    return state;
  }

  return {
    ...state,
    newId: newId + 1,
    taskTitle: '',
    tasks: [...tasks, { id: newId, title }],
  };
},
```

2020-10-17 16:05 UTC, Knoa0405 commented on src/InputContainer.test.jsx
> +  beforeEach(() => jest.clearAllMocks());
맞네요~! 반환값이 없으면 화살표함수를 쓰면 잘못된 거였네요

2020-10-18 13:45 UTC, merged