week4-1 refactor todo app using redus
CodeSoom/week4-assignment-1 pull request #32
Opened 2020-10-13 07:21 UTC by JamieShin0201

안녕하세요^^

아샬님 강의를 보며 스스로 진행해보았습니다.

계속 맞춰보며 진행하니 아샬님이 리팩토링한것과 같아졌네요..

더 살펴보면서 필요한 부분이 있으면 리팩토링 하겠습니다.

감사합니다ㅎㅎ

2020-10-13 13:44 UTC, hannut91 requested changes
잘해주셨네요 ㅎㅎ 배운대로만 계속 잘 연습해보시면 좋을 것 같아요

2020-10-13 13:44 UTC, hannut91 commented on src/reducer.js
> +}
`if`나 `switch`문 없이 이 문제를 해결할 수 있을까요?

2020-10-13 13:44 UTC, hannut91 commented on src/reducer.test.js
> +    context('without existed task ID', () => {
`with not existed task ID`는 어떨까요?

2020-10-14 05:05 UTC, JamieShin0201 commented
안녕하세요^^

1. 리뷰받은 부분 수정하였습니다 ㅎㅎ
2. InputContainer, ListContainer에 필요한 테스트코드를 추가하였습니다.

감사합니다 ㅎ.ㅎ

2020-10-14 16:11 UTC, hannut91 requested changes

2020-10-14 16:11 UTC, hannut91 commented on src/reducer.js
> +  };
얘네들은 정확히 말하면 `action`들은 아니고 `reducer`긴 해요 ㅎㅎ 상태를 변경하는 역할만 하는 애들이죠.
그리고 이 코드는 `reudcer`함수 안에 없어도 될 것 같아요. 위에다 선언하는건 어떨까요?

2020-10-14 16:11 UTC, hannut91 commented on src/InputContainer.test.jsx
> +});
하나의 테스트에서 너무 많은 일을 하고 있는 것 같아요.
주어진 요소들이 잘 렌더링 되는지, input의 변화시켰을 때 어떤 일이 발생하는지, 추가 버튼을 클릭했을 때 어떤 일이 발생하는지 3가지 일을 하고 있는 것 같아요. 하나의 테스트는 하나만 테스트하도록 하는건 어떨까요? 우리가 하나의 함수는 하나의 일만 하는 것 처럼요

2020-10-15 01:27 UTC, JamieShin0201 commented
안녕하세요^^ 

1. 리뷰 받은부분 수정하였습니다!

계속 코드 살펴보면서 수정할 부분 수정하겠습니다. 

감사합니다 ㅎ.ㅎ

2020-10-16 00:26 UTC, hannut91 approved these changes
좋습니다 ㅎㅎ 충분히 연습하신 것 같아요 ㅎㅎㅎ

2020-10-17 02:30 UTC, merged