Refactor the code that changes state.
CodeSoom/week4-assignment-1 pull request #33
Opened 2020-10-13 14:13 UTC by hyejineee

## 과제 목표
상태 관리를 Redux로 변경해도 모든 컴포넌트 테스트가 통과해야 합니다. 추가로 reducer들에 대한 테스트를 추가해 주세요.

## 제한 조건
모든 기능은 TDD로 구현합니다. 컴포넌트와 reducer에 대한 테스트가 존재해야 합니다. 먼저 테스트를 추가하고 commit 한 뒤 실제 기능을 추가하고 commit합니다. commit 메시지 로그는 아래와 같이 남아야 합니다.
> Restaurant에 대한 테스트를 추가한다.
Restaurant을 구현한다.
Restaurant를 리팩토링한다

- if는 사용할 수 있어도 else 사용하실 수 없습니다. GuardClauses 방법을 사용해주세요.
- switch는 사용하실 수 없습니다.
- let은 사용하실 수 없습니다. const만을 사용하여 문제를 해결해주세요.
- 함수 이름과 변수 이름에 줄임말은 사용하실 수 없습니다. 길더라도 명확하게 써주세요.
- indent(인덴트, 들여쓰기) depth를 1로 유지해주세요. 예를 들어, for문 안에 if문이 있으면 indent depth는 2입니다. depth를 줄이는 좋은 방법은 함수(또는 메소드)를 분리하면 됩니다.

## 요구사항

- [ ] ESLint를 돌린 결과 아무런 문제가 없어야 합니다.
- [ ] 모든 인수 테스트를 통과시켜야 합니다.
- [ ] 한 파일에는 하나의 컴포넌트만 있어야 합니다.
- [ ] 테스트 커버리지 100%를 달성해야 합니다.

---

2020-10-14 15:58 UTC, hannut91 reviewed
강의를 보면서 잘 복습하고 계신 것 같아요 ㅎㅎ 따라치는 것보다 보지 않고 스스로 과제를 수행해보는 연습을 해보시면 더 좋을 것 같아요. 더 힘들겠지만 더 많이 배우실 수 있을거에요

2020-10-15 02:53 UTC, hyejineee commented
@hannut91 넹!! 일단 강의보고 따라하면서 작업하고 revert후에 다시 한번 더 작업하도록 하겠습니다ㅎㅅㅎ 저 이번주는 금,토 쉬는 날이에여!ㅋ큐ㅠㅠ

2020-10-16 00:23 UTC, hannut91 requested changes

2020-10-16 00:23 UTC, hannut91 commented on src/reducer.js
> +}
`if`문이나 `switch`문 사용없이 같은 기능을 구현할 수 있을까요?

2020-10-17 02:16 UTC, hannut91 approved these changes
사소한 수정말고는 더 이상 수정할게 없어보여요 ㅎㅎ 고생하셨어요

2020-10-17 02:16 UTC, hannut91 commented on src/InputContainer.jsx
> +  }));
`taskTitle`밖에 사용하기 있지 않으니 `tasks`는 지워줘도 될 것 같아요

```suggestion
  const { taskTitle } = useSelector((state) => ({
    taskTitle: state.taskTitle,
  }));
```

2020-10-17 02:16 UTC, hannut91 commented on src/reducer.js
> +};
위의 함수들은 상태를 변경하는 함수라서 reducer함수라고 불러요. 그래서 `reducers`가 좀 더 정확할 것 같아요

2020-10-17 02:16 UTC, hannut91 commented on src/reducer.js
> +  }
객체의 property가 있으면 redcuer함수를 실행할려고 하신 것 같아요. 

```js
if (!actions[action.type]) {}
```

간단하게 위와 같이 표현할 수 있을 것 같아요

그리고 
```js
actions[action.type]({ state, action });
```

이렇게만 써줘도 될 것 같아요. action.type이 문자열이기 때문에요

2020-10-17 12:43 UTC, hyejineee commented on src/InputContainer.jsx
> +  }));
넵넵!! 피드백에 대한 수정은 과제2 제출하고 나서 해도 될까요??ㅎㅅㅎ

2020-10-18 12:55 UTC, hannut91 commented on src/InputContainer.jsx
> +  }));
네넵 ㅎㅎ

2020-10-20 13:53 UTC, merged