Week4_1 todo redux TDD
CodeSoom/week4-assignment-1 pull request #34
Opened 2020-10-13 14:55 UTC by saseungmin

## ✌ To-do 리스트 Redux를 사용하여 리팩터링 하기

### 🚀 과제 목표
- [x] 상태 관리를 `Redux`로 변경해도 모든 컴포넌트 테스트가 통과하기
- [x] 추가로 `reducer`들에 대한 테스트를 추가하기

### 🤔 제한 조건
- 모든 기능은 `TDD`로 구현합니다. 
- 컴포넌트와 `reducer`에 대한 테스트가 존재해야 합니다. 
- 먼저 테스트를 추가하고 `commit` 한 뒤 실제 기능을 추가하고 `commit`합니다. 
- `commit` 메시지 로그는 아래와 같이 남아야 합니다.
> Restaurant에 대한 테스트를 추가한다
> Restaurant을 구현한다
> Restaurant를 리팩토링한다

2020-10-13 15:08 UTC, saseungmin commented
#### 아샬님의 영상을 한 번 본 뒤 안보고 구현하고 있는 중에 하고있는 방법이 잘 못 된거 같아서 질문드립니다. ㅠㅠ😢
- 과제의 제한 조건에 테스트를 작성하고 구현하는 것이라고 하는데 현재 코드를 작성하고 있는 형태는 구현을 하고 테스트를 작성하는 거 같아서 일단 `pull request` 올려봅니다..
- 현재 스토어에 리듀서까지 작성을 한 상태인데, 만약 테스트부터 작성해야 한다면 아샬님 영상의 반대로 해야하는 건가요??
영상에서는 리덕스 작성하고 테스트를 작성하는 것으로 보이는데 그렇다면, 리듀서에 대한 테스트를 작성을 하고, 구현을 하는 것이 맞는 것인가요..?
아니면 제가 잘 못 이해하고 있는게 있을까요??

- 조언 부탁드립니다.. 🙏

2020-10-14 15:13 UTC, saseungmin commented
### 📌 현재 진행사항
- `reducer` 테스트까지 구현한 상태입니다.
- 아직 컴포넌트 테스트는 변경하지 않았습니다.

2020-10-14 16:31 UTC, hannut91 requested changes

2020-10-14 16:31 UTC, hannut91 commented on src/reducer.js
> +}
`if`문이나 `switch`문 없이 이 문제를 해결할 수 있을까요?

2020-10-16 00:36 UTC, hannut91 requested changes

2020-10-16 00:36 UTC, hannut91 commented on src/InputContainer.test.jsx
> +    fireEvent.click(getByText(/추가/));
`추가` 버튼이 있는지 위에서도 확인하고, 아래에서 추가 버튼을 클릭하고 있는 것 같아요. 추가 버튼을 클릭한다는 것은 해당 버튼이 이미 있다고 가정하는 것이니까 제 생각에는 테스트를 두 번 하는 것 같아요. 그래서 저는 위의 단정문은 지우는게 좋다고 생각하는데 어떠신가요?

2020-10-16 00:36 UTC, hannut91 commented on src/reducer.js
> +const createAction = (state = initialState, { type, payload }) => {
위의 `reducer`는 여러개니까 `reducers`로 하고, `createAction`은 사실 액션을 만들어주는 애는 아니고 상태를 변경해주는 함수이니까 이 함수 이름을 `reducer`로 하는건 어떨까요

2020-10-16 00:36 UTC, hannut91 commented on src/reducer.test.js
> +      it('tasks가 존재할 때', () => {
`it`에서는 실제로 어떤 일이 일어나는지 기술하는게 좋습니다. 제가봤을 때는 reducer가 정의되어있지 않은 action을 실행할 때 테스트하고 있는 것 같으므로 아래와 같이 하는 것도 괜찮을 것 같아요

```js
context('with undefined action', () => {
  it('returns previous state', () => {
    ...
  });
});
```

2020-10-17 15:51 UTC, hannut91 approved these changes

2020-10-17 15:51 UTC, hannut91 commented on src/InputContainer.test.jsx
> +  }));
각 테스트는 다른 테스트에 영향을 줘서도 안되고, 다른 테스트에 의존해서도 안됩니다. 그러면 테스트를 유지보수하기 굉장히 어려워지고 테스트가 의도치 않게 동작할 수 있습니다.  예를들어서

```js
describe('Component', () => {
  const handleClick = jest.fn();
  
  const renderComponent = () => render((
    <Component onClick={handleClick} />
  ));
  
  test('click test', () => {
    const { getByText } = renderComponent();
    
    fireEvent.click(getByText('클릭'));
    
    // 통과
    expect(handleClick).toBeCalled();
  });
  
  text('non click test', () => {
    const { getByText } = renderComponent();
    
    // 실패!
    expect(handleClick).not.toBeCalled();
  });
});
```

테스트 코드가 위에서부터 순서대로 실행이 되는데 위의 테스트에서 이미 클릭을 해서 handleClick은 호출이 된 상태가 되었습니다. 그래서 클릭이 안되어있어야 할 테스트에서 실패하게 됩니다. 이 것은 우리가 의도한게 아니라 테스트 환경을 적절히 초기화 시키지 않아서 생긴 문제입니다. 따라서 위의 문제는 아래와 같이 초기화를 해주어야 합니다.

```js
describe('Component', () => {
  const handleClick = jest.fn();
  
  // 테스트가 실행되기 전에 실행  
  beforeEach(() => {
    // mocking 함수들을 초기화
    jest.clearAllMocks();
  });
  
  const renderComponent = () => render((
    <Component onClick={handleClick} />
  ));
  
  test('click test', () => {
    const { getByText } = renderComponent();
    
    fireEvent.click(getByText('클릭'));
    
    // 통과
    expect(handleClick).toBeCalled();
  });
  
  text('non click test', () => {
    const { getByText } = renderComponent();
    
    // 실패!
    expect(handleClick).not.toBeCalled();
  });
});
```

mocking한 함수 뿐만 아니라 테스트끼리 상태가 공유되는 것들은 모두 초기화해주는게 좋습니다. `dispatch`를 초기화 해주고 `useDispatch`와 `useSelector`를 초기화로직에 추가하는게 좋을 것 같습니다.

```js
beforeEach(() => {
  jest.clearAllMocks();
});

beforeEach(() => {
  useDispatch.mockImplementation(() => dispatch);

  useSelector.mockImplementation((selector) => selector({
    taskTitle: '아무것도 하지 않기 3',
  }));
});
```
See also
  - https://jestjs.io/docs/en/jest-object#jestclearallmocks
  - https://jestjs.io/docs/en/setup-teardown

2020-10-18 03:25 UTC, saseungmin commented on src/InputContainer.test.jsx
> +  }));
- 친절한 설명 감사합니다!! 🌈
- 안그래도 week4_2를 하다가 계속 그 전 테스트의 `dispatch`가 호출되었다고 나와서 한참 고민하다가 결국 각 테스트에 `useSelector`를 넣어주게 되었습니다.
- `week4_2`를 수정할 수 있을 거 같습니다. 감사합니다.🙏

2020-10-19 14:43 UTC, merged