[Week4] Assignment 1 - Todo List Redux를 사용하여 리팩터링 하기
CodeSoom/week4-assignment-1 pull request #35
Opened 2020-10-13 15:02 UTC by wjy5446

## 목표
- 상태관리를 `Redux`로 변경해도 모든 컴포넌트 테스트가 통과해야합니다. 추가로 `reducer`들에 테스트를 추가해주세요.

## 조건
- 모든 기능은 TDD로 구현합니다. 컴포넌트와 reducer에 대한 테스트가 존재해야 합니다. 먼저 테스트를 추가하고 commit 한 뒤 실제 기능을 추가하고 commit합니다. commit 메시지 로그는 아래와 같이 남아야 합니다.

> Restaurant에 대한 테스트를 추가한다
>
> Restaurant을 구현한다
>
> Restaurant를 리팩토링한다
>
> ...

## 진행사항
- [x] Redux를 사용한 컴포넌트의 unit 테스트가 통과될 수 있도록 수정  
- [ ] reducer에 대한 테스트 코드 추가 

-> 주로 아샬님께서 강의해주신 내용을 보고 코드를 작성했습니다.

2020-10-14 15:48 UTC, Kihyun92 requested changes
좋습니다! 강의를 보며 따라해보는 것도 많은 도움이 되지만, 강의를 보지 않고도 과제 조건에 맞게 진행해 보시면 더 기억에 남을 것 같아요 :)

2020-10-14 15:48 UTC, Kihyun92 commented on src/App.test.jsx
> +
tasks에 대해서도 테스트 해주면 좋을 것 같아요~

2020-10-14 15:48 UTC, Kihyun92 commented on src/index.jsx
> +  ),
```suggestion
    <Provider store={store}>
      <App />
    </Provider>,
```

이렇게 작성해도 괜찮을 것 같아요~

2020-10-14 15:48 UTC, Kihyun92 commented on src/reducer.js
> +  }
`reducer`내에서 `if`를 사용하지 않고 처리할 방법은 없을까요~?

2020-10-15 04:33 UTC, wjy5446 commented on src/reducer.js
> +  }
switch를 사용하면 되지 않을 까요?

2020-10-15 15:37 UTC, Kihyun92 commented on src/reducer.js
> +  }
`if`와 `switch`같은 조건문을 사용하지 않고 할 수 있는 방법이 없을지에 대해서 말씀드렸던 거였어요 ㅎㅎ

여러 방법이 있겠지만, [Object Literal lookups](https://ultimatecourses.com/blog/deprecating-the-switch-statement-for-object-literals)도 방법이 될 수 있을 것 같네요~

2020-10-16 11:51 UTC, wjy5446 commented on src/reducer.js
> +  }
Object Literal lookup도 있군요 !! 감사합니다.!!

2020-10-16 13:42 UTC, wjy5446 commented on src/index.jsx
> +  ),
간단하게 작성할 수 있군요. 감사합니다.

2020-10-19 13:32 UTC, Kihyun92 commented
fail 나는 부분이 있는 것 같아요~ 수정해주시면 `approve` 하겠습니다~

2021-01-17 12:56 UTC, merged