[4주차 과제1] To-do 리스트 Redux를 사용하여 리팩터링 하기
CodeSoom/week4-assignment-1 pull request #36
Opened 2020-10-13 22:38 UTC by juunini

# 과제 목표
상태 관리를 Redux로 변경해도 모든 컴포넌트 테스트가 통과해야 합니다. 추가로 reducer들에 대한 테스트를 추가해 주세요.

2020-10-14 16:12 UTC, Kihyun92 requested changes
좋습니다~ 강의를 보고 잘 작성해주신것 같아요! 👍  
이번 과제에도 약간의 제한 사항이 있었는데요 ㅎㅎ 가능하다면 제한 사항에 맞춰 다시 해보셔도 좋고, 조금 더 리펙토링 해보셔도 좋을 것 같습니다~
![image](https://user-images.githubusercontent.com/35797540/96016268-82a09a00-0e83-11eb-8ac8-b645510683ef.png)

2020-10-14 16:12 UTC, Kihyun92 commented on src/App.test.jsx
> +  expect(getByText(/Task-2/)).not.toBeNull();
`Task-1`, `Task-2`로 테스트를 해도 문제는 없지만, tasks의 변화에 대응하지 못할 것 같아요. `forEach`를 사용하면 조금 더 `Side effect를 일으키고, 모든 항목을 순회한다`는 의도를 드러내어 표현할 수 있을 것 같아요~

- https://refactoring.com/catalog/replaceMagicLiteral.html

2020-10-14 16:12 UTC, Kihyun92 commented on src/index.jsx
> +  ),
```suggestion
    <Provider store={store}>
      <App />
    </Provider>,
```
이렇게 처리해도 괜찮을 것 같아요~

2020-10-14 16:12 UTC, Kihyun92 commented on src/reducer.js
> +  }
`reducer`내에서 `if`를 쓰지 않고 작성할 방법이 있을까요~?

2020-10-14 16:12 UTC, Kihyun92 commented on src/reducer.test.js
> +        }, deleteTask(1));
중복 코드는 조금 더 추상화 해줄 수 있을 것 같아요~

2020-10-17 14:39 UTC, juunini commented on src/reducer.js
> +  }
객체로 변경하여 보았습니다.

2020-10-18 14:02 UTC, Kihyun92 approved these changes

2020-10-19 13:26 UTC, merged