Refactor code to separate concerns
CodeSoom/week4-assignment-1 pull request #37
Opened 2020-10-14 04:46 UTC by smilee

## 과제 목표

상태 관리를 Redux로 변경해도 모든 컴포넌트 테스트가 통과해야 합니다. 추가로 reducer들에 대한 테스트를 추가해 주세요.

## 제한 조건

- 모든 기능은 TDD로 구현합니다. 컴포넌트와 reducer에 대한 테스트가 존재해야 합니다. 먼저 테스트를 추가하고 commit 한 뒤 실제 기능을 추가하고 commit합니다. commit 메시지 로그는 아래와 같이 남아야 합니다.

```
Restaurant에 대한 테스트를 추가한다

Restaurant을 구현한다

Restaurant를 리팩토링한다

...
```

- if는 사용할 수 있어도 else 사용하실 수 없습니다. GuardClauses 방법을 사용해주세요.
- switch는 사용하실 수 없습니다.
- let은 사용하실 수 없습니다. const만을 사용하여 문제를 해결해주세요.
- 함수 이름과 변수 이름에 줄임말은 사용하실 수 없습니다. 길더라도 명확하게 써주세요.
- indent(인덴트, 들여쓰기) depth를 1로 유지해주세요. 예를 들어, for문 안에 if문이 있으면 indent depth는 2입니다. depth를 줄이는 좋은 방법은 함수(또는 메소드)를 분리하면 됩니다.

## 요구사항

- [ ] ESLint를 돌린 결과 아무런 문제가 없어야 합니다.
- [ ] 모든 인수 테스트를 통과시켜야 합니다.
- [ ] 한 파일에는 하나의 컴포넌트만 있어야 합니다.
- [ ] 테스트 커버리지 100%를 달성해야 합니다.

2020-10-14 16:05 UTC, hannut91 requested changes

2020-10-14 16:05 UTC, hannut91 commented on src/App.test.jsx
> +import { useSelector } from '../__mocks__/react-redux';
여기서는 mocks에 있는 것을 import하는 것이 아닌 `react-redux`를 import하는게 맞을 것 같아요.

2020-10-14 16:05 UTC, hannut91 commented on src/reducer.js
> +}
`if`나 `switch`문 없이 이 문제를 해결할 수 있을까요?

2020-10-16 00:24 UTC, hannut91 requested changes

2020-10-16 00:24 UTC, hannut91 commented on src/reducer.js
> +    }[type]();
이 객체를 따로 서언한 후 실행하는건 어떨까요?

2020-10-16 07:44 UTC, smilee commented on src/reducer.js
> +    }[type]();
함수로 뺐습니다.

2020-10-16 07:45 UTC, smilee commented on src/reducer.js
> +}
object literal로 해결했습니다.

2020-10-16 07:45 UTC, smilee commented on src/App.test.jsx
> +import { useSelector } from '../__mocks__/react-redux';
고쳤습니다.

2020-10-17 02:30 UTC, hannut91 requested changes

2020-10-17 02:30 UTC, hannut91 commented on src/App.test.jsx
> +  useDispatch.mockReturnValue(mockDispatch);
변수를 선언한 곳과 사용하는 곳의 거리가 가까우면 좋을 것 같아요. 

```js
const mockDispatch = jest.fn();
useDispatch.mockReturnValue(mockDispatch);

useSelector.mockImplementation((selector) => selector({
  tasks,
}));
```

2020-10-17 02:30 UTC, hannut91 commented on src/InputContainer.test.jsx
> +  useDispatch.mockReturnValue(dispatch);
각 테스트마다 항상 동일한 환경에서 테스트가 되어야 합니다. 그렇지 않으면 테스트가 다른 테스트에 영향을 주게 됩니다. 그러면 테스트 코드들을 유지보수하기 어려워지고 의도치 않은 결과가 나올 수 있습니다. 따라서 다음과 같이 하는게 좋을 것 같아요.

```js
beforeEach(() => {
  useSelector.mockImplementation((selector) => selector({
    tasks,
  }));
  useDispatch.mockReturnValue(dispatch);
});
```

2020-10-17 02:30 UTC, hannut91 commented on src/reducer.js
> +  }
`action.type.indexOf('@@') > -1`이건 어떤 의미인가요?

2020-10-17 02:30 UTC, hannut91 commented on src/reducer.js
> +  const { type, payload } = action;
reducer 함수가 많아지고 사용되는 상태들이 많을수록 이쪽은 점점 거대해질 것 같아요. 
reducer함수에게 현재 상태와 action을 넘겨줘서 각각 처리하도록 하는건 어떨까요?

```js
const reducers = {
  changeTaskTitle: (state, action) => ({
    ...state,
    taskTitle: action.payload.value,
  }),
}

export default function reducer(state = initialState, action) {
  if (!action || action.type.indexOf('@@') > -1) {
    return state;
  }

  return reducers[action.type](state, action)
}
```

2020-10-18 10:51 UTC, smilee commented on src/App.test.jsx
> +  useDispatch.mockReturnValue(mockDispatch);
반영했습니다!

2020-10-18 10:53 UTC, smilee commented on src/InputContainer.test.jsx
> +  useDispatch.mockReturnValue(dispatch);
반영했습니다!

2020-10-18 10:55 UTC, smilee commented on src/reducer.js
> +  }
initialize할 때 들어오는 액션 타입의 시작 부분입니다~ 😄

2020-10-18 11:00 UTC, smilee commented on src/reducer.js
> +  const { type, payload } = action;
반영했습니다!

2020-10-18 13:01 UTC, hannut91 approved these changes
고생하셨습니다 ㅎㅎ 다음번에는 TDD를 조금 더 연습해보시면 좋을 것 같아요

2020-10-18 13:01 UTC, hannut91 commented on src/InputContainer.jsx
> +    tasks: state.tasks,
여기는 없어도 될 것 같네요 ㅎㅎ

2020-10-19 07:45 UTC, smilee commented on src/InputContainer.jsx
> +    tasks: state.tasks,
반영했습니다!

2020-10-20 13:48 UTC, merged