[week4-assignment-1] To-do 리스트 Redux를 사용하여 리팩터링 하기
CodeSoom/week4-assignment-1 pull request #38
Opened 2020-10-14 15:56 UTC by goodzzong

## 목표
- 상태 관리를 Redux로 변경해도 모든 컴포넌트 테스트가 통과해야 합니다. 추가로 reducer들에 대한 테스트를 추가해 주세요.

## 제한 조건
- 모든 기능은 TDD로 구현합니다.
- 컴포넌트와 reducer에 대한 테스트가 존재해야 합니다. 
- 먼저 테스트를 추가하고 commit 한 뒤 실제 기능을 추가하고 commit합니다.

2020-10-14 17:07 UTC, hannut91 requested changes

2020-10-14 17:07 UTC, hannut91 commented on src/store.js
> +import reducer from './reducer';
위에 빈 줄 하나를 추가해서 라이브러리 import와 로컬 파일 import를 분리해주면 좋을 것 같아요

2020-10-14 17:07 UTC, hannut91 commented on src/reducer.test.js
> +    context('without existed task ID', () => {
`with not existed task ID`는 어떨까요?

2020-10-14 17:07 UTC, hannut91 commented on src/reducer.test.js
> +  });
변화를 테스트 해야하는데 지금은 모두 텍스트가 같아서 테스트의 의도를 파악하기 어려운 것 같아요. 올바르게 동작하는지도 파악하기 어렵구요. 어떤 변화가 일어나는지 집중해서 테스트를 작성해보시면 도움이 되실 것 같아요

2020-10-14 17:07 UTC, hannut91 commented on src/reducer.test.js
> +    context('when there is a no task title', () => {
task title이 없다기 보다 비어있다는 걸 명시하는건 어떨까요? `empty`라던가

2020-10-15 00:20 UTC, goodzzong commented on src/reducer.test.js
> +    context('when there is a no task title', () => {
테스트 단위의 이름을 지을 때 어떤 식으로 하면 좋은지에 대한 방법이 있을까요?

2020-10-15 00:22 UTC, goodzzong commented on src/reducer.test.js
> +  });
감이 잘 안잡히는데 예를 들어 처음 상태는 이것 이었지만  액션이 발생해서 이렇게 변했다라는걸 코드로 표현해보면 좋을까요?

2020-10-16 00:50 UTC, hannut91 commented on src/reducer.test.js
> +  });
초기상태가 `New Title`인데 `New Title`로 업데이트해서 `New Title`이 되도록 업데이트를 하는 것을 테스트하면, 혹시 코드를 제대로 작성못해서 업데이트가 안되더라도 테스트가 통과하게 돼요.

2020-10-16 00:52 UTC, hannut91 commented on src/reducer.test.js
> +    context('when there is a no task title', () => {
https://www.betterspecs.org/

이 문서를 보면 좋은데 

https://ko.javascript.info/testing-mocha

이 문서도 한 번 보시면 좋을 것 같아요

2020-10-16 00:54 UTC, hannut91 requested changes

2020-10-16 00:54 UTC, hannut91 commented on src/reducer.test.js
> +    it('should update action', () => {
`should`라는 말은 사용안하는게 좋습니다. 만약 꼭 `should`라는 말을 사용하고 싶으시면 it 함수 대신 sholud함수를 사용할 수 있긴 합니다.

2020-10-16 00:54 UTC, hannut91 commented on src/reducer.test.js
> +    });
액션의 type이 없을 때, 초기 상태가 없을 때, 초기 상태와 액션이 둘 다 있을 때 테스트를 하신 것 같아요. 각각 명확하게 테스트로 분리하는건 어떨까요

2020-10-16 01:19 UTC, goodzzong commented on src/reducer.test.js
> +    context('when there is a no task title', () => {
감사합니다!

2020-10-16 01:20 UTC, goodzzong commented on src/reducer.test.js
> +  });
제가 잘못 입력을 했군요! 초기상태를 아예 똑같이 넣었네요;; 감사합니다

2020-10-16 01:25 UTC, goodzzong commented on src/reducer.test.js
> +    });
분리해보겠습니다!

테스트를 하다보니 각각 테스트를 해야하는 컴포넌트들 입장에서 생각 해야 할 것 같은데 자꾸 모든걸 알고 있는 제 입장에서 생각하니 헷갈리는 것 같네요

2020-10-20 13:51 UTC, hannut91 commented
슬랙 채널에 회고를 남겨주셔서 머지합니다!

2020-10-20 13:51 UTC, merged