[4주차|과제1] To-do 리스트 Redux 사용하여 리팩터링하기 코드리뷰 부탁드립니다.
CodeSoom/week4-assignment-1 pull request #4
Opened 2020-06-24 15:47 UTC by jiunkoo

1. 기본적인 패키지 설치
2. App.jsx 컴포넌트의 상태/랜더링 기능 분리
3. store.js 파일 생성
4. TDD로 UpdateTaskTitle, Add Task, Delete Task 구현

위와 같이 작업했습니다.

** 앞으로의 계획
1. App.test.jsx에서 상태 코드 삭제
2. App.test.jsx의 테스트에 맞추어 App.jsx에 기능 구현
3. 작성된 코드 action.js 분리하여 전체 리팩토링

2020-06-24 22:22 UTC, hannut91 reviewed
테스트 작성하신 단계도 좋고, 테스트도 명확해서 다 좋네요! 계속 진행해주세요!

2020-06-24 22:22 UTC, hannut91 commented on src/index.jsx
> +import { Provider } from 'react-redux';
위에 빈 줄 하나를 추가해서 리액트 라이브러리와 리덕스 라이브러리 임포트를 구분해주면 좋을 것 같아요

2020-06-24 22:22 UTC, hannut91 commented on src/index.jsx
> +import store from './store';
위에 빈 줄 하나를 추가해서 컴포넌트 임포트와 스토어 임포트를 구분해주면 좋을 것 같아요

2020-06-24 22:22 UTC, hannut91 commented on src/reducer.test.js
> +    context('without task title', () => {
위에 빈 줄 하나를 추가해주세요

2020-06-24 22:22 UTC, hannut91 commented on src/store.js
> +export default store;
아래 빈 줄 하나를 추가해주세요. 이 아래에 빈 줄 하나를 추가하는 이유는 깃헙에서 컨벤션 때문에 그런건데요. 현재 코드는

```js
export default store
```

인데 만약 아래에 새로운 코드를 추가하면 깃헙은 이렇게 구분합니다.

```js
+ export default store;
+
+ something new code
```

왜냐하면 `export default store`가 `export default store\n`가 됐기 때문이에요. 그래서 맨 마지막에 빈 줄 하나를 넣은 상태에서 새로운 코드를 작성하면

```js
+
+ something new code
```

만 나와서 깃헙에서 더 보기 좋은 코드가 됩니다. 그래서 깃헙에서는 마지막에 빈 줄 하나를 추가하지 않으면 이렇게 기호로 표시해줘요

2020-06-24 22:27 UTC, hannut91 requested changes

2020-06-24 22:27 UTC, hannut91 commented on src/reducer.js
> +};
`if`나 `switch` 없이 이 문제를 해결할 수 있을까요?

2020-06-27 12:21 UTC, jiunkoo commented
** reducer branch 60% 문제
reducer.js의 45-46번째 라인이 cover되지 않습니다.
도와주세요ㅠㅠ...

2020-06-27 13:46 UTC, jiunkoo commented
드디어 테스트 통과ㅠㅠ

코드 리뷰 부탁드립니다.

2020-06-27 14:10 UTC, hannut91 approved these changes
고생하셨습니다 ㅎㅎ 커밋을 작게 나눠서 작성하는 연습이 많이 되어 있으신 것 같아요. 다음 과제를 진행해주세요.

2020-06-27 14:10 UTC, hannut91 commented on src/App.test.jsx
> +};
이 테스트에서 사용할 함수가 `getByText, getByPlaceholderText`이 두개만 있다는 것을 강조하기 위해 사용하셨나요? 바로 `render`함수 결과를 반환해도 똑같은 결과가 나올거에요.

```js
const renderApp = () => render(<App />);
```

이러면 함수안의 식이 이미 충분히 로직을 설명하고 있어서 `renderApp`을 안써도 될거에요

2020-06-27 14:10 UTC, hannut91 commented on src/App.test.jsx
> +    useDispatch.mockImplementation(() => dispatch);
테스트에서 같은 로직이 반복되고 있는 것 같아요. 중복을 제거해주는 건 어떨까요?

2020-06-27 14:10 UTC, hannut91 commented on src/reducer.js
> +};
이렇게 작성할 수 있을거에요
```js
const reducers = {
  deleteTask(state, action) {
    const { tasks } = state;
    return {
      ...state,
      tasks: tasks.filter((task) => task.id !== action.payload.id),
    };
  },
 
  addTask(state, action) {
    ...
  }
}
```

2020-06-27 14:10 UTC, hannut91 commented on src/reducer.test.js
> +  test('initialState', () => {
어떤걸 테스트하는지 잘 드러나지 않는 것 같아요. 초기 상태가 없을 때 초기 상태를 사용한다는 것을 나타내고 싶으셨더 거죠?

```js
context('when initial state is undefined', () => {
  it('returns initial state', () => {
    ...
  });
});
```

2020-06-27 14:10 UTC, hannut91 commented on src/reducer.test.js
> +  });
```js
context('with undefined action', () => {
  it('returns previous state', () => {
    ...
  });
});
```

2020-06-27 14:10 UTC, hannut91 commented on src/reducer.test.js
> +  });
```js
context('with updateTaskTitle action', () => {
  it('updates taskTitle', () => {
    ...
  });
});
```

2020-06-28 00:53 UTC, merged