즐거운 리팩토링 😎
CodeSoom/week4-assignment-1 pull request #42
Opened 2021-02-15 02:37 UTC by dodoongtak

2021-02-15 12:20 UTC, dodoongtak commented
![image](https://user-images.githubusercontent.com/77006427/107945653-474ddd80-6fd3-11eb-9301-79d795926083.png)

커밋 순서가 뒤죽박죽이 됬습니다 ㅠㅠ 

테스트를 추가한다가 첫번째 커밋이 구현한다인데..

(이미 로컬에서 떠나가버린... commit들이여...)

채널에서도 남겼지만 여기에서도 동일한 질문을 남겨볼께요! 

영상에서 아샬님이 다음과 같이 리팩토링을 진행하셨는데...
1.기존 App state를 Redux로 변경하는 작업 (store, action 등등)
2. Redux 테스트 작성
3. List 컴포넌트를 Container로 분리. redux 상태관리중 List에 해당되는 부분을 App 에서 Container로
4.List 테스트코드 작성
5. Input 컴포넌트를 Container로 분리. redux 상태관리중 Input에 해당되는 부분을 App 에서 Container로
6. Input 테스트코드 작성
7. Page 삭제 -> App

리팩토링하고 결과물은 같지만 영상과는 다르게 Test를 우선 작성하여 
 TDD Cycle로 변경을 시도해보면서 커밋을 제출하는게 중요 포인트라고 파악 되는데,

핀트를 잘못짚었을까요?

저는 우선 reducer에 관한 test를 먼저 작성해봤습니다.

2021-02-15 15:37 UTC, Kihyun92 requested changes
> 리팩토링하고 결과물은 같지만 영상과는 다르게 Test를 우선 작성하여
TDD Cycle로 변경을 시도해보면서 커밋을 제출하는게 중요 포인트라고 파악 되는데,
핀트를 잘못짚었을까요?
저는 우선 reducer에 관한 test를 먼저 작성해봤습니다.

![image](https://user-images.githubusercontent.com/35797540/107966071-b08f1a00-6fee-11eb-8eb3-fbda8576cea0.png)

저희의 의도대로 해주고 계신 것 같습니다 👍🏼 

강의를 보고 따라하는것도 도움이 되지만, 직접 해보는건 훨씬 도움이 되죠 ㅎㅎ

배웠던 것을 떠올려 보면서 과제를 진행해보시면 좋을 것 같아요 :)

2021-02-15 15:37 UTC, Kihyun92 commented on src/actions.js
> +export function uopdateTaskTitle(taskTitle) {
오타가 있네요~ ☺️

2021-02-15 15:37 UTC, Kihyun92 commented on src/reducer.js
> +  return state;
`if`나 `switch`문 없이 이 문제를 해결할 수 있을까요?

2021-02-15 15:37 UTC, Kihyun92 commented on src/reducer.test.js
> +      expect(state.taskTitle).toBe('New Title');
라인 사이에 공백이 추가되면 좋을 것 같아요~

2021-02-15 15:37 UTC, Kihyun92 commented on src/reducer.test.js
> +      }, addTask());
불필요한 공백이 추가된 것 같네요. 제거해주세요 :)

2021-02-15 17:06 UTC, dodoongtak commented on src/reducer.js
> +  return state;
도전...

2021-02-16 01:43 UTC, dodoongtak reviewed
reducer 함수 prototype에 object를 넣어 if문을 제거해보았습니다. :)

2021-02-16 01:43 UTC, dodoongtak commented on src/reducer.js
>      if (!taskTitle) return state;
taskTitle을 삼항연산자로 return 을 묶을 수 있지만 가독성이 현저히 떨어져보여 해당 if statment는 유지 하였습니다. 🙌

2021-02-16 01:45 UTC, dodoongtak commented on src/reducer.js
> +  return state;
[제거완료](https://github.com/CodeSoom/react-week4-assignment-1/pull/42#pullrequestreview-590833164) ✔

2021-02-16 10:48 UTC, dodoongtak commented on src/reducer.js
> +  return state;
## 문제점 
- object에 key가 undefined 일시 argument를 애초에 못넘김.

## 해결 방법
- 삼항연산자로 해당 키가 있는지 확인, 없으면 state를 그대로 return

## 꺠달은 점
- 이 후 App 구현 중 브라우저에서 작동이 안된 걸 파악. 
- reducer를 우선으로 test하고 구현 할 시 이런 불상사가 있는걸로 파악. 
- reducer를 TDD로  최우선으로 작성해야되는걸 아닌걸 인지.

## 예상 리뷰 
- 삼항연산자 없이 처리가 가능할까요?

Why?
- 함수가 퓨어하지 않음(?!!?!?!??!) 

다른 방도가 도저히 생각이 나지 않아 다른 구현사항으로 우회하여 돌진.

2021-02-16 10:49 UTC, dodoongtak commented on src/reducer.js
>      if (!taskTitle) return state;
https://github.com/CodeSoom/react-week4-assignment-1/pull/42#discussion_r576727494 해당 If문 관련 업데이트 메세지입니다!

2021-02-16 11:01 UTC, dodoongtak commented
## Q1

App test에 useSelector를 mocking function으로 대체하여 tasks에 object를 넣어 test를 패스하게 만들었는데, 이 테스트의 목적이 어떤 것인지 감이 안잡힙니다!! 

- useSelector라는 함수가 이런 object를 받을 수 있다 테스트에 명시해주는 목적인가요?

- 기존 Assertion(expect(getByText(/추가/)).not.toBeNull();) 와 같이 useSelector를 이용해 다른 Assertion을 만들어야 될까요?

## Q2 

꼭 100% 커버리지 달성이 product의 퀄리티를 완성시키는게 아니라고 윤석님이 슬랙에 글을 남겨주셨습니다. 
다만 이번 과제는 아무래도 사이즈가 작다보니, 100% 달성이 되야 CI에 패스 할 수 있다고도 이어 말씀해주셨습니다.

하나의 TDD cycle을 돌릴 떄, 100%로 만들고 다음 테스트로 넘어가는게 좋을까요? 
아니면 해당 컴포넌트들의 Test들을 우선 전체적으로 작성하고, 하나하나 다시 살펴보며 끌어올리는게 좋을까요?

정답이 있는 질문이 아니지만, 기현님은 어떻게 진행하시는 궁금하여 커버리지 질문 남겨보아요. ㅎㅎ

2021-02-16 14:10 UTC, Kihyun92 requested changes

2021-02-16 14:10 UTC, Kihyun92 commented on src/reducer.js
>      if (!taskTitle) return state;
넵 괜찮아 보입니다 ㅎㅎ 👍🏼

2021-02-16 14:10 UTC, Kihyun92 commented on src/reducer.js
> +reducer.actionType = {
`const reducers = { ... }`와 같이 선언하여 사용하는건 어떨까요?

2021-02-16 14:12 UTC, Kihyun92 commented on src/reducer.js
> +  return state;
해당 키가 없는 경우엔 state를 리턴해주는 처리가 필요하기 때문에 삼항연산자로 잘 처리해 주신 것 같습니다 ㅎㅎ

2021-02-16 14:33 UTC, Kihyun92 commented
>Q1
App test에 useSelector를 mocking function으로 대체하여 tasks에 object를 넣어 test를 패스하게 만들었는데, 이 테스트의 목적이 어떤 것인지 감이 안잡힙니다!!
useSelector라는 함수가 이런 object를 받을 수 있다 테스트에 명시해주는 목적인가요?
기존 Assertion(expect(getByText(/추가/)).not.toBeNull();) 와 같이 useSelector를 이용해 다른 Assertion을 만들어야 될까요?

App test에서 무엇을 테스트하려 하셨나요? 

`App test에 useSelector를 mocking function으로 대체하여 tasks에 object를 넣어 test를 패스하게 만들었는데` 이렇게 처리한 이유가 답이 될 수 있을 것 같네요 ㅎㅎ

존재하는 상태값이 화면에 올바르게 노출되는지 확인하는 목적이 있을 것 같아요. 어떻게 테스트 할 수 있을까요?

>Q2
꼭 100% 커버리지 달성이 product의 퀄리티를 완성시키는게 아니라고 윤석님이 슬랙에 글을 남겨주셨습니다.
다만 이번 과제는 아무래도 사이즈가 작다보니, 100% 달성이 되야 CI에 패스 할 수 있다고도 이어 말씀해주셨습니다.
하나의 TDD cycle을 돌릴 떄, 100%로 만들고 다음 테스트로 넘어가는게 좋을까요?
아니면 해당 컴포넌트들의 Test들을 우선 전체적으로 작성하고, 하나하나 다시 살펴보며 끌어올리는게 좋을까요?
정답이 있는 질문이 아니지만, 기현님은 어떻게 진행하시는 궁금하여 커버리지 질문 남겨보아요. ㅎㅎ

이 부분은 개인마다 그리고 상황마다  다를 것 같아요 ㅎㅎ 애매할 수 있지만 저는 가능하면 커버리지 100%로 만들고 다음 테스트로 넘어가는 것 같습니다. 그래야 어떤 기능이 추가 됐을때, 테스트 코드도 추가로 작성해야한다는 걸 알 수 있을 것 같아요~

2021-02-17 12:13 UTC, dodoongtak commented
## 의심되는 것
커버리지 100%를 달성했지만... 모든 코드의 테스트를 100%로 커버 했다고는 장담하지 못하겠네요 . 🔴🔴🔴🔴

TDD cycle로 정확히 커밋을 남기고 싶었지만, 테스트 작성을 하고 구현을 할 시 에 또 다른 Refactoring이 필요없게 구현을 해서 Refacotring 커밋을 남길 수가 없었습니다. 

기존 코드가 이미 있는 상태에서 refactoring을 진행하기에 발생 된거 같아 보여요. 따로 코드를 아예 삭제하거나 위에서부터 전부 다 Refacotring 을 건드리니 더욱 더 어려웠습니다.

## 발전 해보고 싶은 것
1. 지금 테스트 예시 들이 전부 복수가 아닌 단수의 케이스들로만 구성 되있습니다. 복수로 테스트를 해봐야 정확히 코드가 원하는대로 작동하는지 장담 할 수 있다고 보입니다. 

예시) 2개의 Task에서 1개의 Task를 삭제 할 때 삭제 된 Task는 리스트에 보이지가 않는다.

2. Reducers action을 포함시키는 객체에 state라는 인자를 반복적으로 받습니다. 커링을 활용해서 Refactoring 하는게 좋아보이는데, 저번 리뷰에 언급을 따로 안하셨는데, 굳이 안만드는 이유가 있으니 말씀을 안남겨주셨나 생각해봅니다.

2021-02-17 13:53 UTC, Kihyun92 commented on src/reducer.js
> +reducer.actionType = {
설명이 부족했던 것 같아 DM으로 의논 했던 내용 남겨봅니다 ㅎㅎ

따로 객체로 선언하는게 좋다고 말씀드린 이유는 몇가지가 있을 것 같아요. 일단 보면 지금 reducer는 함수죠. 자바스크립트 특성상 원시타입이던, 함수던 상관없이 메서드 혹은 속성들을 추가할 수 있습니다. 그걸 이용해서 조금 더 reducer와 연결되어 있다는 의미를 나타내려고 하신 것 같아요.
하지만 일반적으로 함수의 역할을 생각했을때 따로 속성값을 가지고 있는게 적절하지 않은 것 같아요.
추가적으로 재사용을 위해서 따로 `const reducers = { ... }` 와 같이 사용하라는것 보단, `재할당`이 불가능하도록 한다는 의도였습니다.
지금과 같은 구조라면 다른 동료가 `actionType`에 어떤 수정을 할 수 있는 가능성이 있을 것 같아요

2021-02-17 14:27 UTC, Kihyun92 requested changes
커버리지가 100%이지만, 안심하지 못하는 원인이 무엇인가요? 테스트는 본인이 안심 할 수 있어야해요. 어떤 부분 때문에 안심이 안되는지 고민해보시고 보완해보시면 좋을 것 같아요 :)
 
그리고 `발전해보고 싶은 것`에 남겨주신 내용들은 제가 미처 다 보지 못한 부분인 것 같아요 🙇🏻‍♂️
여유가 되신다면 말씀하신 부분들도 작업해보시고 같이 의논해봐도 좋을 것 같네요 :)

앞으로도 리뷰가 더 필요한 부분이 있다면 말씀해주셔요!

2021-02-17 14:27 UTC, Kihyun92 commented on src/InputContainer.test.jsx
> +    useDispatch.mockImplementation(() => dispatch);
반복되는 코드는 리팩터링해주면 좋을 것 같아요~

2021-02-17 14:27 UTC, Kihyun92 commented on src/InputContainer.test.jsx
> +    fireEvent.change(getByDisplayValue(/TDD는 언제나 새롭다/), { target: { value: '거짓말 아님' } });
두개의 인자를 받는데 두번째 인자는 객체 형태라서 이 경우에는 가독성을 위해 줄바꿈 처리해주는건 어떨까요?
```suggestion
    fireEvent.change(getByDisplayValue(/TDD는 언제나 새롭다/), {
      target: {
        value: '거짓말 아님' 
      }
    });
```

2021-02-17 14:27 UTC, Kihyun92 commented on src/InputContainer.test.jsx
> +  it('adds a task to tasks upon Clicking 추가 button', () => {
개인적으로 잘 읽히지 않는 것 같아요.

`adds a task when click 추가 button` 과 같은 느낌은 어떤가요? 영어 어렵네요..😭

2021-02-17 14:27 UTC, Kihyun92 commented on src/reducer.test.js
> +  context('with action type', () => {
가능하면 `context` 간의 단어가 대응 되면 좋을 것 같아요.

`when has no action type` <-> `when has action type`

`with empty action type` <-> `with action type`

2021-02-17 14:53 UTC, dodoongtak commented on src/reducer.js
> +reducer.actionType = {
여기 금일 [커밋](https://github.com/CodeSoom/react-week4-assignment-1/pull/42/commits/1e5cb1cea6fd3020faa998c94620b1f9af157df5 )에 반영해서 업데이트 해놨습니다 ㅎㅎㅎㅎ

제가 기현님이 말씀하신 내용 이외 다르게 처리 된건가요??? 😮

2021-02-17 15:08 UTC, dodoongtak commented on src/InputContainer.test.jsx
> +  it('adds a task to tasks upon Clicking 추가 button', () => {
"웹에서 동작을 해주는 행동으로 description을 작성 하면 좋겠다 - 3주 차 과제 리뷰 中"  
 참고하여 의미에 맞게 영문으로 작성하였습니다. 
 
InputCotainer adds a task upon clicking 추가 button  => **"InputContainer는 추가 버튼을 클릭 할 시 Task를 추가해준다. "**
InputCotainer adds a task when clicking 추가 button => **"InpuContainer는 추가 버튼을 클릭 할 때 Task를 추가해준다"**

upon -> after 
when -> at the time 
요런 늬앙스의 차이라. 

어음... 음... 이번 과제 리뷰 하실 때 보기 어려우시다면 한글로 다 교체 작업 해볼께요!

2021-02-17 15:34 UTC, Kihyun92 commented on src/InputContainer.test.jsx
> +  it('adds a task to tasks upon Clicking 추가 button', () => {
오 하나 배웠네요 🙏

형탁님의 의도만 잘 전달되는 문구면 좋은 것 같아요 ㅎㅎ

2021-02-18 14:19 UTC, Kihyun92 approved these changes
고생하셨습니다! 과제 1은 피드백 드릴게 더 없는 것 같네요 👍🏼 

이제 과제 2에 집중해봅시다 :)

2021-02-23 14:52 UTC, merged