Redux 1 수강 후 첫 PR
CodeSoom/week4-assignment-1 pull request #46
Opened 2021-02-15 15:53 UTC by ParkYoungHoon

Redux 1 강의 보면서 따라해봤습니다.
남은 강의 학습 후 더 진행해보겠습니다.

2021-02-16 14:39 UTC, Kihyun92 reviewed
강의를 보고 따라하는것도 도움이 되지만, 다 보고 직접 해보는건 훨씬 도움이 될 것 같아요 ㅎㅎ

2021-02-16 15:49 UTC, ParkYoungHoon commented
일단 강의 보면서 진행 해보고, 코드를 전체적으로 분석을 해봐야 할것 같습니다 ㅎㅎ
익숙해지면 응용해서 기능을 추가해서 직접 해보겠습니다!

2021-02-17 13:49 UTC, Kihyun92 commented
과제 요구사항에 맞게 커밋을 쪼개보는 건 어떨까요?
![image](https://user-images.githubusercontent.com/35797540/108213473-68990000-7172-11eb-96b4-41093c28ef7d.png)

2021-02-17 13:51 UTC, Kihyun92 requested changes

2021-02-17 13:51 UTC, Kihyun92 commented on src/reducer.js
> +  }
`if`나 `switch`를 사용하지 않고 해결할 수 있을까요?

2021-02-19 15:15 UTC, Kihyun92 commented
@ParkYoungHoon 님, 혹시 어떻게 진행되고 있나요~? 어려운점이 있거나 의논이 필요하다면 편하게 말씀주세요! 😊

2021-05-16 09:30 UTC, merged