Use redux
CodeSoom/week4-assignment-1 pull request #48
Opened 2021-02-16 10:27 UTC by datalater

4주차 1번 과제 제출합니다.

## 현재 진행 과정

아직 완성되지 않았습니다만 일단 완성된 부분까지 제출합니다.

현재 진행 과정은 다음과 같습니다:

* App 컴포넌트에 있는 상태 관리 코드를 리덕스로 바꿀 것이다.
* App 컴포넌트에 있는 상태 관리 코드를 리팩토링 할 것이다. 
* 그런데 리팩토링 하기 전에 리팩토링이 잘 되는지 검사해줄 테스트 코드가 없다.
* 따라서 App 컴포넌트의 상태 관리 코드에 대한 테스트를 작성한다.

## TODO

* 리듀서 테스트 코드를 작성한다.

## 궁금한 점

## 요청 받은 코드 리뷰 목록

## 메타인지

### 내가 모르는 것은 무엇인가

### 내가 알게 된 것은 무엇인가

### 어떻게 하면 더 나을까
 
## 주간회고

2021-02-16 14:42 UTC, Kihyun92 reviewed
커밋 메시지를 잘 작성해주시는 것 같아요! 👍🏼 

강의를 보고 따라하는것도 도움이 되지만, 직접 해보는건 훨씬 도움이 되죠 ㅎㅎ

배웠던 것을 떠올려 보면서 과제를 진행해보시면 좋을 것 같습니다 :)

2021-02-17 01:47 UTC, datalater commented
네 강의 보고 따라 치고 있지 않고요 ㅎㅎ 복기하면서 하고 있습니다

2021-02-17 06:39 UTC, datalater commented
# 질문

![image](https://user-images.githubusercontent.com/8105528/108165468-f3a7d500-7135-11eb-97f3-a4e4cc67ce28.png)

위 커버리지를 보면 App 컴포넌트에서 핸들러 함수가 테스트 되지 않은 부분이 있습니다. 리덕스 container 컴포넌트, presentational 컴포넌트로 리팩토링하기 전에 현재 코드에서 App 테스트 커버리지를 100%로 채워보고 싶습니다. 

그런데 useSelector는 가짜로 구현했지만 useDispatch를 가짜로 구현하지 않아서 dispatch가 함수가 아니라는 오류가 뜹니다.

useDispatch를 useSelector처럼 mockImplementation으로 구현해보고 싶은데 이렇게 되면 store도 가짜로 또 구현해야 하는 게 아닌가 싶어요. 어떻게 접근해보면 될까요?

2021-02-17 06:49 UTC, datalater commented
dispatch가 함수가 아니라는 오류가 발생하는 상황을 다시 재현하기 위해 5ba6dca 커밋을 추가했습니다.

2021-02-17 06:51 UTC, datalater commented
# 질문

![image](https://user-images.githubusercontent.com/8105528/108166704-ea1f6c80-7137-11eb-864b-76195137b1b3.png)


위 커버리지를 보면 App 컴포넌트에서 핸들러 함수가 테스트 되지 않은 부분이 있습니다. 리덕스 container 컴포넌트, presentational 컴포넌트로 리팩토링하기 전에 현재 코드에서 App 테스트 커버리지를 100%로 채워보고 싶습니다. 

그런데 useSelector는 가짜로 구현했지만 useDispatch를 가짜로 구현하지 않아서 dispatch가 함수가 아니라는 오류가 뜹니다.

![image](https://user-images.githubusercontent.com/8105528/108166801-0b805880-7138-11eb-802c-6ff126abf084.png)

useDispatch를 useSelector처럼 mockImplementation으로 구현해보고 싶은데 이렇게 되면 store도 가짜로 또 구현해야 하는 게 아닌가 싶어요. 어떻게 접근해보면 될까요?

2021-02-17 08:45 UTC, datalater commented
테스트 커버리지 결과를 첨부합니다.

![image](https://user-images.githubusercontent.com/8105528/108178574-edbaef80-7147-11eb-99ab-16f18a6c5481.png)

2021-02-17 14:53 UTC, Kihyun92 requested changes

2021-02-17 14:53 UTC, Kihyun92 commented on src/App.test.jsx
> +  it('shows "추가" text', () => {
실제론 버튼이니까 `shows "추가" button`은 어떤가요?

2021-02-17 14:53 UTC, Kihyun92 commented on src/InputContainer.test.jsx
> +  }));
`beforeEach`함수를 사용해서 테스트가 실행될 때마다 항상 일정한 상태에서 시작할 수 있도록 해주는게 좋을 것 같아요.
그러지 않으면 테스트가 다른 테스트들에 영향을 미칠 수 있고, 그러면 테스트가 올바르게 동작하지 않거나 유지보수하기 힘들어질 거에요.

```
beforeEach(() => {
  useDispatch.mockImplementation(() => dispatch);

  useSelector.mockImplementation((selector) => selector({
    taskTitle: 'New Title',
  }));
});

```

2021-02-17 14:53 UTC, Kihyun92 commented on src/reducer.js
> +  }
`if`나 `switch`를 사용하지 않고 해결할 수 있을까요?

2021-02-17 14:53 UTC, Kihyun92 commented on src/reducer.test.js
> +    context('without previous state offered', () => {
이 경우엔 `context`보단 `it`으로 처리하는게 맞을 것 같습니다. 혹은 위쪽에 테스트를 `context`로 감싸주는게 좋을 것 같아요.

다른 테스트들도 확인해주세요~

`with <-> without`
`when log in <-> when log out`
처럼 같은 맥락에서 별개의 사례일 때 `context`를 사용합니다.

context 사용법은 아래 문서와 아샬님의 문서를 참고해주세요.

- https://www.betterspecs.org/
- https://github.com/ahastudio/til/blob/main/blog/2018/12-08-given-when-then.md

2021-02-17 14:53 UTC, Kihyun92 commented on src/reducer.test.js
> +  describe('unregisteredAction', () => {
이 부분은 보다 상위에서 context로 처리해주는건 어떨까요? 

``` jest
context('when has unregistered action type', () => { ... })

context('when has action type', () => {
  // updateTaskTitle, addTask 등 처리
})
```

2021-02-18 10:43 UTC, datalater commented on src/InputContainer.test.jsx
> +  }));
아하 감사합니다!!

2021-02-18 10:45 UTC, datalater commented on src/reducer.js
> +  }
object literal을 사용하도록 변경해보겠습니다!

2021-02-18 10:46 UTC, datalater commented on src/reducer.test.js
> +    context('without previous state offered', () => {
아하.. 대칭적일 때 사용하는 것이라 생각하면 되겠군요. 감사합니다! 반영할게요.

2021-02-18 10:46 UTC, datalater commented on src/reducer.test.js
> +  describe('unregisteredAction', () => {
이해되었습니다. 감사합니다. 반영할게요!

2021-02-18 10:47 UTC, datalater commented on src/App.test.jsx
> +  it('shows "추가" text', () => {
그렇네요 ㅎㅎ 반영하겠습니다!

2021-02-19 11:31 UTC, datalater commented on src/reducer.test.js
> +  describe('unregisteredAction', () => {
그러면 

```jsx
describe('reducer', () => {
  context('with unregistered action type', () => {
  })

  context('with registered action type', () => {
    describe('updateTaskTitle', () => {
      context('without previous state', () => {
        it('changes task title using initalState', () => {});
      });

      context('with previous state', () => {
        it('changes task title', () => {});
      });
    });
  })

})
```

위와 같이 될 것 같은데, `describe-context-describe-context-it` 이런 식으로 사용해도 괜찮은가요?

2021-02-19 11:36 UTC, datalater commented on src/App.test.jsx
> +  it('shows "추가" text', () => {
2a72a76

2021-02-19 11:37 UTC, datalater commented on src/InputContainer.test.jsx
> +  }));
df7a985

2021-02-19 11:37 UTC, datalater commented on src/reducer.js
> +  }
22d7fc2

2021-02-19 11:37 UTC, datalater commented on src/reducer.test.js
> +    context('without previous state offered', () => {
c386d31

2021-02-19 15:34 UTC, Kihyun92 commented on src/reducer.test.js
> +  describe('unregisteredAction', () => {
개인적으로는 중간에 `without previous state offered ~~`를 제외하면 계층구조로 잘 나뉜 것 같다고 생각이 드는것 같긴해요. 😅

그런데 중요한건 내가 테스트를 통해 뭘 보여주고 싶은지 같아요.ㅎㅎ 본인이 보기에 더 명확하게 전달이 가능한 구조로 테스트를 구현해보는게 좋을 것 같습니다😊

2021-02-19 15:39 UTC, Kihyun92 approved these changes
좋습니다! TDD cycle에 조금 익숙해지셨나요? ㅎㅎ 

[테스트 구조 관련해서 커맨트](https://github.com/CodeSoom/react-week4-assignment-1/pull/48#discussion_r579273685) 남겼습니다. 확인해보시고 여유가 되시면 수정해보셔도 좋을 것 같아요 :)

2021-02-21 02:35 UTC, datalater commented on src/reducer.test.js
> +  describe('unregisteredAction', () => {
그러네요 `without previous state offered ~~` 이 부분을 보니 테스트가 중복되어 있네요 수정해서 올리겠습니다!

피드백 감사합니다!!

2021-02-21 02:37 UTC, datalater commented
테스트 구조 수정했습니다. 놓치고 있던 포인트들 피드백 주셔서 정말 감사합니다!!

![image](https://user-images.githubusercontent.com/8105528/108613863-1f2e0680-7439-11eb-958e-ee144cd2d5b9.png)

2021-03-03 15:51 UTC, merged