Refactor with redux
CodeSoom/week4-assignment-1 pull request #49
Opened 2021-02-16 11:34 UTC by bluel00

테스트를 통과시키기 쉽지 않네요.

에러가 나서 잡고 있습니다.

2021-02-16 16:05 UTC, Kihyun92 requested changes

2021-02-16 16:05 UTC, Kihyun92 commented on src/reducer.js
> +  }
`if`를 사용하지 않고 해결할 수 있을까요? 🤔

2021-02-16 16:06 UTC, Kihyun92 commented
의논이 필요하면 편하게 말씀주세요~

2021-02-17 07:16 UTC, bluel00 commented on src/reducer.js
> +  }
네 룩업테이블 패턴으로 변경했습니다.

2021-02-17 12:07 UTC, bluel00 commented
- reducer의 테스트를 완성했습니다.
- reducer의 if문을 제거했습니다.

## Todo
- Page 컴포넌트 분리

2021-02-17 13:25 UTC, bluel00 commented
- 관심사에 따라 InputContainer와 ListConatiner로 분리

2021-02-17 15:19 UTC, Kihyun92 requested changes
`red-green-refactoring` 사이클을 지키려고 노력해주시는 것 같아요 👍🏼 

그런데 TST, CLN이 무슨 말인가요?🤔

커밋 메시지에 prefix를 붙인다면 RED, GREEN, REFACTORING으로 해도 좋을 것 같네요~

2021-02-17 15:19 UTC, Kihyun92 commented on src/InputContainer.test.jsx
> +    );
테스트간에 중복되는 코드가 있는 것 같아요~ 리팩터링 해보시면 좋을 것 같습니다

2021-02-17 15:19 UTC, Kihyun92 commented on src/InputContainer.test.jsx
> +  it(' 할일을 입력한다. ', () => {
테스트의 의도가 조금 더 드러나면 좋을 것 같아요~

`Given-When-Then`의 형식을 참고해보셔도 좋을 것 같습니다 :) 

- https://github.com/ahastudio/til/blob/main/blog/2018/12-08-given-when-then.md

2021-02-17 15:19 UTC, Kihyun92 commented on src/List.jsx
> +  if (!tasks?.length) {
이렇게 수정하신 이유가 있나요?

부정문으로 예외처리하는 것은 보는 사람에게 한번 더 생각하게끔해서 가능하면 긍정문으로 예외처리를 권장합니다.

2021-02-17 15:19 UTC, Kihyun92 commented on src/reducer.js
> +  };
if 문을 사용하지 않고 객체로 처리해보셨군요!! 👍🏼 

`reducer` 함수 바깥에 선언해도 좋을 것 같네요~

그리고 네이밍은 `actionsTable ` 보단 `reducers`는 어떨까요?

2021-02-17 15:19 UTC, Kihyun92 commented on src/reducer.js
> +  return actionsTable[(action?.type)] ? actionsTable[(action?.type)]() : state;
```suggestion
  return actionsTable[action?.type] ? actionsTable[action?.type]() : state;
```
소괄호로 감싸주지 않아도 되지 않나요?

그리고 action에 type이 없는 경우를 위해 reducer 함수에서 action에 default value로 초기값을 넣어줘도 될 것 같네요 ㅎㅎ

2021-02-18 05:41 UTC, bluel00 commented on src/InputContainer.test.jsx
> +    );
네 공통적으로 사용되는 dispatch 부분을 
befereEach로 처리했습니다.

2021-02-18 05:42 UTC, bluel00 commented on src/InputContainer.test.jsx
> +  it(' 할일을 입력한다. ', () => {
> Given - 700와트 전자렌지를 준비하고, 3분이란 시간이 주어졌을 때
> When - 주어진 시간동안 전자렌지를 돌리면
> Then - 요리가 완성된다.
> 

Given-When-Then 형식으로 수정했습니다.

2021-02-18 05:44 UTC, bluel00 commented on src/List.jsx
> +  if (!tasks?.length) {
네 다시 긍정문으로 수정했습니다.

2021-02-18 05:46 UTC, bluel00 commented on src/reducer.js
> +  };
함수명 고치고 파라미터를 받아서 처리하도록 수정했습니다.

2021-02-18 05:48 UTC, bluel00 commented on src/reducer.js
> +  return actionsTable[(action?.type)] ? actionsTable[(action?.type)]() : state;
말씀대로 초기값을 넣으니
action이 없어 발생하는 참조에러에 대한 처리도 필요 없어지는군요.

2021-02-18 13:26 UTC, Kihyun92 requested changes

2021-02-18 13:26 UTC, Kihyun92 commented on src/InputContainer.test.jsx
> +}
추후 다른 describe를 필요하는 테스트가 추가됐을 경우를 생각해보면 해당하는 describe 안에 있는게 좋을 것 같아요~

2021-02-18 13:26 UTC, Kihyun92 commented on src/ListContainer.test.jsx
> +      expect(queryByText(/뭐라도 하기 #1/)).not.toBeNull();
forEach를 통해 다른 tasks들을 테스트해줘도 좋겠네요 ㅎㅎ

2021-02-18 13:26 UTC, Kihyun92 commented on src/ListContainer.test.jsx
> +    }));
이 부분도 중복되는 것 같은데 해결할 수 있을까요?

2021-02-19 01:16 UTC, bluel00 commented on src/InputContainer.test.jsx
> +}
네 위치를 옮겼습니다.

2021-02-19 01:17 UTC, bluel00 commented on src/ListContainer.test.jsx
> +      expect(queryByText(/뭐라도 하기 #1/)).not.toBeNull();
수정했습니다.

2021-02-19 01:24 UTC, bluel00 commented on src/ListContainer.test.jsx
> +    }));
케이스마다 다른 tasks가 필요해 beforeEach에는 넣지 못하고
함수로 빼봤습니다.🤔

2021-02-19 15:43 UTC, Kihyun92 approved these changes
리뷰 드린것보다 더 잘 반영해주신 것 같아요! 👍🏼 

TDD cycle이 좀 익숙해지셨나요? ㅎㅎ 과제 2에 집중해보죠 :)

2021-02-23 14:54 UTC, merged