Refactor a TodoList with Redux and TDD
CodeSoom/week4-assignment-1 pull request #5
Opened 2020-06-24 19:08 UTC by daadaadaah

리뷰 요청드립니다.

우선 reducer만 TDD 진행해봤어요~

2020-06-24 22:35 UTC, hannut91 requested changes
테스트도 잘 작성해주셨고 커밋도 잘 작성해주셨네요 ㅎㅎ reducer에서 `if`나 `switch` 없이 문제를 해결해보세요

2020-06-24 22:35 UTC, hannut91 commented on src/reducer.js
> +  }
`if`나 `switch`없이 이문제를 해결할 수 있을까요?

2020-06-24 22:35 UTC, hannut91 commented on src/reducer.test.jsx
> +    context('without task ID', () => {
위에 빈 줄 하나를 추가해주세요

2020-06-24 22:35 UTC, hannut91 commented on src/reducer.test.jsx
> +    it('change a new task title', () => {
테스트 이름이 잘못 된 것 같아요

2020-06-25 12:21 UTC, daadaadaah commented
일단 오늘 작업까지만 리뷰 요청드립니다.

추후에 container 관련 작업 추가할게요~~

2020-06-25 12:40 UTC, hannut91 commented on src/reducer.test.jsx
> +    it('change a new task title', () => {
여기서 `new`가 의미하는바가 무엇인지 모르겠어요

2020-06-25 12:40 UTC, hannut91 commented on src/reducer.test.jsx
> +    context('with taskTitle', () => {
`when taskTitle is not empty`는 어떤가요?

2020-06-25 12:40 UTC, hannut91 commented on src/reducer.test.jsx
> +    context('without taskTitle', () => {
`when taskTitle is empty`는 어떤가요?

2020-06-25 12:40 UTC, hannut91 commented on src/reducer.test.jsx
> +    context('without task ID', () => {
`task ID`없이가 아니라 존재하지 않는 task ID를 입력했을 때죠?

2020-06-25 12:49 UTC, daadaadaah commented on src/reducer.test.jsx
> +    it('change a new task title', () => {
new 뺄게요~

2020-06-25 20:43 UTC, daadaadaah commented on src/ListContainer.test.jsx
> +          });
이 코드가 불변성을 지키는 코드인지 아닌지 헷갈려요ㅠㅠ

2020-06-26 00:11 UTC, hannut91 commented on src/ListContainer.test.jsx
> +          });
`initState`를 변경하지 않고 새로운 객체를 만들고 있으니 괜찮습니다

2020-06-26 00:19 UTC, hannut91 approved these changes
고생하셨습니다 ㅎㅎ 다 좋은데 조금 마음에 걸리는 것은 테스트 이름에 너무 구체적인 구현이 들어가 있는 것 같아요. 구현이 조금만 바껴도 테스트의 이름이 바뀌네요.

2020-06-26 10:42 UTC, closed without merging

2020-06-26 10:55 UTC, daadaadaah commented
#5 피드백 참고!