4주차 1번째 과제
CodeSoom/week4-assignment-1 pull request #60
Opened 2021-05-24 07:08 UTC by yujong-lee

1번째 과제 완료했습니다.

두 가지 의문이 있습니다.
1. `App.test.jsx`에서 중복제거의 문제
`dispatch`를 `mocking`하는 부분이 중복되어 리팩터링 책에 나온 예시대로 `beforeEach`로 중복을 제거해봤습니다. 그런데 `let`을 사용하지 않고 싶은데 어떻게 하는 것이 좋을까요? `given`으로 숨기는 것도 될 것은 같은데 별로 좋지는 않아보이고 뾰족한 방법이 떠오르지 않네요. 
```js
  let dispatch;
  beforeEach(() => {
    dispatch = jest.fn();
    useDispatch.mockImplementation(() => dispatch);
  });
```

2. `onChange` 이벤트 객체의 문제

현재 `updateTaskTitle`을 아래와 같이 테스트하고 있습니다.
```js
// 'codesoom'을 타이핑
    expect(dispatch).toHaveBeenLastCalledWith({
      type: 'UpdateTaskTitle',
      payload: {
        taskTitle: 'm',
      },
    });
```

그런데 처음부터 이렇게 하려고 했던 것은 아니고, 아래와 같이 하려고 했는데 테스트가 통과를 못해서 바꿔준 것입니다.
```js
// 'codesoom'을 타이핑
    expect(dispatch).toHaveBeenLastCalledWith({
      type: 'UpdateTaskTitle',
      payload: {
        taskTitle: 'codesoom',
      },
    });
```
`onChange`에서 받는 이벤트 객체에서 `event.target.value`를 해서 `taskTitle`을 업데이트 해주니까 `c, co, cod, code, codes, ... codesoom` 이렇게 찍혀야 할 것 같은데(콘솔로 찍어봐도 그렇습니다.) 테스트할 때 오류 메시지는 `c, o, d, e, s, o, o, m` 이런 순서로 `dispatch`가 `call`된다고 하네요. 제가 무엇을 잘못 생각하고 있는 것일까요?

2021-05-24 14:47 UTC, Kihyun92 requested changes
오,, 벌써 이 만큼을 진행하셨군요 👍🏼 👍🏼  리덕스에 익숙하신 것 같네요 ㅎㅎ

Redux의 도입을 했기 때문에 App 컴포넌트의 관심사가 무엇인지 다시 한번 고민해볼 때인 것 같습니다. 
이전 과제에서 유종님께서 Container/Presentation 모델을 적용해주셨던 기억이 나요. 컴포넌트들의 관심사에 따라서 기존 구조들을 한번 변경해보시면 어떨까요?

추가로 질문에 대한 답변은 해당 코드에 남겼습니다! 확인 부탁드려요~

2021-05-24 14:47 UTC, Kihyun92 commented on src/App.test.jsx
> +  });
```suggestion
  const dispatch = jest.fn();
  
  beforeEach(() => {
    jest.clearAllMocks();
    useDispatch.mockImplementation(() => dispatch);
  });
```

위와 같이 매 테스트 시작 전에 mocking한 것들을 clear 시켜주도록해서 해결 할 수 있을 것 같네요~

2021-05-24 14:47 UTC, Kihyun92 commented on src/App.test.jsx
> +    });
이 부분은 좀 더 확인해봐야 알겠지만, `userEvent type`의 경우엔 말씀하신대로 각각 call이 생기는 군요.

`fireEvent change`를 사용하면 `toBeCalledWith`를 통해 한번에 확인 할 수 있었어요. 

`userEvent`에도 뭔가 option을 통해 한번에 입력하도록 할 수 있을 것 같은데 저도 userEvent 에 익숙치 않아 이 부분은 좀더 찾아봐야겠습니다.

2021-05-24 14:47 UTC, Kihyun92 commented on src/App.test.jsx
> +    ));
매번 비슷하게 반복되는 이 코드도 beforeEach에서 처리해주면 좋겠네요~

2021-05-24 14:47 UTC, Kihyun92 commented on src/actions.js
> +  type: 'UpdateTaskTitle',
혹시 액션의 타입을 대문자로 시작하는 이유가 있나요?

2021-05-24 14:47 UTC, Kihyun92 commented on src/reducer.js
> +  }
switch를 사용하지 않고 해결할 수 없을까요?

2021-05-24 14:47 UTC, Kihyun92 commented on src/reducer.test.js
> +  });
이 부분은 위쪽에 위치하게하고, 위쪽 테스트들을 `'with valid action '`과 같은 context로 묶어주는건 어떤가요?

2021-05-24 14:47 UTC, Kihyun92 commented on src/App.test.jsx
> +  it('updates taskTitle wiht input control', () => {
오타가 있는 것 같아요~

2021-05-25 01:57 UTC, yujong-lee commented on src/App.test.jsx
> +    });
원래는 제 실수라고 생각했었는데 코멘트 달아주신 것을 보고 조금 찾아보니 [이미 논의가 된 적이 있네요.](https://github.com/testing-library/user-event/issues/387) 여러번 수정이 되었는데 아직 문제가 있나봐요. 이슈를 다 읽어봤는데 100퍼센트 이해가 가지는 않네요. 

이왕이면 `userEvent`를 사용하려고 했는데, 여기서는 `fireEvent`를 사용하는 것이 좋겠어요.

2021-05-25 02:45 UTC, yujong-lee commented on src/App.test.jsx
> +  it('updates taskTitle wiht input control', () => {
수정했습니다.

2021-05-25 02:46 UTC, yujong-lee commented on src/App.test.jsx
> +  });
아 clear하는 방법이 있었군요. 
```js
jest.clearAllMocks(); // 이것도 좋지만
dispatch.mockClear(); // 여기서는 이렇게하는 것이 어떤가요?

2021-05-25 02:51 UTC, yujonglee commented on src/reducer.test.js
> +  });
좋아요. 수정했습니다.

2021-05-25 03:01 UTC, yujong-lee commented on src/actions.js
> +  type: 'UpdateTaskTitle',
원래 `CONSTANT_VALUE`와 같이 하는 것을 어디서 봤었는데, 그렇게 하면 뭔가 가독성이 떨어지는 것 같아서 그냥 그렇게 수정해놓은 것 같네요. 진작 네이밍 컨벤션을 찾아보고 이름을 지을 것 그랬어요.

네이밍 컨벤션에 관해 많은 자료를 찾아봤는데, `redux` 공식 문서에서 제공하는 `style-guide`가 제일 좋은 것 같아요. [여기](https://redux.js.org/style-guide/style-guide#write-action-types-as-domaineventname)내용을 참고해서 수정했습니다. 리덕스 툴킷에서 이런 식으로 자동으로 생성이 됐었는데, 다 이유가 있었네요.

2021-05-25 03:25 UTC, yujong-lee commented on src/reducer.js
> +  }
리덕스 툴킷을 이용하거나 함수를 반환하는 객체를 이용하면 될 것 같아요.  일단은 객체를 이용하는 것으로 수정했습니다.

2021-05-25 03:54 UTC, yujong-lee commented on src/App.test.jsx
> +    ));
수정했습니다.

2021-05-25 11:59 UTC, yujong-lee commented
자잘한 수정 이후 컨테이너/프레젠테이셔널 컴포넌트를 도입했습니다.
이미 다 짜놓은 상태에서 도입하는 작업이 간단하지는 않았는데, 작은 단위로 나누어서 리듬을 느끼면서 진행하니 점점 진전이 되면서 완성이 되었네요.

2021-05-25 13:32 UTC, Kihyun92 commented on src/App.test.jsx
> +  });
말씀하신대로 지금은 dispatch만 clear 해주는게 좋겠군요! 😄

2021-05-25 13:35 UTC, Kihyun92 commented on src/App.test.jsx
> +    });
넵 계속해서 이슈가 발생하는 부분 같군요 🤔 

좀 더 이슈를 파악해보고 추후에 `userEvent`로 적용해봐도 좋을 것 같습니다.

2021-05-25 14:18 UTC, Kihyun92 commented
> 자잘한 수정 이후 `Container/Presentation`모델을 도입했습니다.
> 이미 다 짜놓은 상태에서 도입하는 작업이 간단하지는 않았는데, 작은 단위로 나누어서 리듬을 느끼면서 진행하니 점점 진전이 되면서 완성이 되었네요.
> 
> 제가 전에 `Container/Presentation` 모델을 몇번 써보기도 하고, 지금도 도입해보면서 이렇게 UI쪽이랑 상태관리/비즈니스 로직을 분리하는 것은 좋다고 느껴지는데요.
> 
> 이전에 리액트를 공부한지 얼마 되지 않았을 때(지금도 얼마 되지는 않았지만) 리액트 훅이 생긴 이후로는 굳이 컴포넌트를 나눌 필요없다는 글을 접했었는데([예시](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0)) 이제 다시 기억이 나네요.
> 
> 코드를 다 수정한 뒤에 생각이 나서 이제야 다시 찾아보고 생각해보려고 하는데, 혹시 이런 주제에 관한 트레이너님의 생각이 궁금합니다.

우선 좋은 글 공유해주셔서 감사합니다 👍🏼  

관심사를 분리한다는 점에서 굉장히 유용한 패턴이라고 생각해요. 문서에도 나오지만, 자연스럽게 `Presentation/Container`로 분리하는게 좋죠.

Dan의 말처럼 동일하게 리액트의 커스텀 훅을 사용해서 관심사를 분리해줄 수 있습니다. 지금은 관심사의 분리가 어떤 관점에서 이루어지는지를 고민해보는 단계라고 생각하시면 좋을 것 같습니다. ㅎㅎ 

추후에 과제에서 커스텀 훅을 직접 다뤄 보셔도 좋을 것 같네요~ 😊

관련해서 코드숨 슬랙 채널에 공유해서 의논해봐도 좋을 것 같군요! 앞으로도 이런 의논점이 있다면 공유해주셔요 ㅎㅎ

2021-05-25 14:32 UTC, Kihyun92 requested changes
리뷰 드린 것보다 더 잘 반영해주신 것 같군요 👍🏼

2021-05-25 14:32 UTC, Kihyun92 commented on src/App.jsx
> +    <TodoPage />
지금은 기능이 많지 않아서 App 과 TodoPage 컴포넌트의 관심사가 비슷한 것 같아요.

TodoPage 컴포넌트로 한번 더 분리할 필요 없이 App 컴포넌트에서 작업해도 될 것 같은데 어떤가요?

2021-05-25 14:32 UTC, Kihyun92 commented on src/presentational/Input.test.jsx
> +});
describe 로 감싸주는게 좋겠네요~

2021-05-26 00:33 UTC, yujong-lee commented on src/App.jsx
> +    <TodoPage />
수정했습니다.

2021-05-26 00:35 UTC, yujong-lee commented on src/presentational/Input.test.jsx
> +});
수정했습니다.

2021-05-26 13:54 UTC, Kihyun92 approved these changes
더 드릴 피드백이 없어 보이네요 👍🏼

2021-05-31 15:51 UTC, merged