4주차 과제1 (To-do 앱 Redux 사용하여 리팩터링하기)
CodeSoom/week4-assignment-1 pull request #61
Opened 2021-05-24 12:42 UTC by seong-dodo

안녕하세요.
오늘 과제 시작이 늦어져서 현재 진행사항까지 올립니다.

- `Redux 전환 과정 1` -  initialState 변수 할당

지금부터 추가로 진행하여 내일은 마감시간 내 최대한 많이 해서 제출하겠습니다~

2021-05-24 13:33 UTC, Kihyun92 reviewed
빠른 PR 좋습니다 👍🏼 

강의를 보고 따라하는것도 도움이 되지만, 직접 해보는건 훨씬 도움이 되죠 ㅎㅎ

![image](https://user-images.githubusercontent.com/35797540/119355265-06571a80-bce0-11eb-8bf5-aa4295a43da6.png)

배웠던 것을 떠올려 보면서 과제 조건에 맞게 진행해보시면 좋을 것 같아요~ 😊

2021-05-25 12:30 UTC, seong-dodo commented
https://github.com/CodeSoom/react-week4-assignment-1/pull/61#pullrequestreview-666740861

안녕하세요. 
피드백 주신 내용 참고하여 과제 진행하였습니다. 

오늘 updateTaskTitle, addTask 테스트 코드를 먼저 추가 한 후 기능 구현을 해보았습니다.
addTask 테스트 추가 후 기능을 구현해보았는데 기능 구현 과정에서 테스트 코드가 잘못 작성됨을 알게 되었습니다. 
테스트 코드를 완벽하게 만들지 못해서 이런 문제가 발생하여 기능구현 과정에서 테스트 코드를 수정하면서 TDD로 시작은 했지만 TDD가 아닌 TDD가 되었네요... 😢 😢 

다음 기능 개발에는 꼭 TDD 싸이클을 지켜보도록 하겠습니다... 🔥 🔥  🔥

2021-05-25 13:23 UTC, Kihyun92 commented
영상을 다 보시고 처음부터 직접 해보셨군요!! 💯 

완성된 기능 위주로 생각하시기보단, 하나씩 작게 진행하더라도 테스트가 항상 통과하도록 해보세요~

예를 들면 `updateTaskTitle`에 대한 테스트 코드를 작성하고 나서 컴포넌트를 만들어 나가는게 아니라 당장 컴포넌트를 `render` 하는 것 부터 하나씩 만들어나가시면 좋아요. 
그러다보면 updateTaskTitle을 만들어야할 것이고, 추후 상태 관리가 복잡해지면 `Redux` 로 관리하게 될거에요.

`RED - GREEN - REACTORING` 을 짧게 가져가려면 어떻게 하면 좋을지 고민해보시면서 다음 작업부터 적용해보면 좋을 것 같아요~

2021-05-26 12:50 UTC, seong-dodo commented
https://github.com/CodeSoom/react-week4-assignment-1/pull/61#issuecomment-847866326

감사합니다 😆 
강의를 보고 기억력을 되살려 차근차근 해보았는데 완성된 기능 위주가 아닌 정말 처음부터 테스트 코드를 먼저 작성하고 기능 구현을 해본다는 생각으로 하나씩 작게 진행하도록 더 많은 고민이 필요한 것 같네요..
당장 컴포넌트를 render 하는 것 부터 하나씩 `RED - GREEN - REACTORING` 사이클로  과제2에 적용해보겠습니다.

이번 과제1는 커버리지 100% 달성할 수 있도록 추가 작업하여 올리도록 하겠습니다.

2021-05-26 14:35 UTC, Kihyun92 requested changes
두번째 과제도 기다리겠습니다~😄

2021-05-26 14:35 UTC, Kihyun92 commented on src/reducer.js
> +  }
`if`를 사용해서 action의 type에 따라 처리해주셨군요!

`object literal lookup`을 사용해보는 것도 좋을 것 같습니다~

- https://ultimatecourses.com/blog/deprecating-the-switch-statement-for-object-literals

2021-05-28 13:49 UTC, seong-dodo commented on src/reducer.js
> +  }
안녕하세요. 과제2, 과제1 커버리지 완성까지 하고 피드백 반영하려고 합니다 ㅠㅠ 
이번 과제 제한조건에 맞춰 수행 및 리덕스 이해가 느려서 아직 피드백 해주신 내용에 대해 공부하지 못하였습니다 ㅜㅜ

2021-05-28 14:25 UTC, Kihyun92 commented on src/reducer.js
> +  }
넵 의논이 필요한 부분이 있다면 말씀주세요!

2021-05-28 15:02 UTC, Kihyun92 requested changes

2021-05-28 15:02 UTC, Kihyun92 commented on src/InputContainer.test.jsx
> +  }));
```suggestion
beforeEach(() => {
  dispatch.mockClear();
  useDispatch.mockImplementation(() => dispatch);

  useSelector.mockImplementation((selector) => selector({
    taskTitle: 'New Title',
  }));
});

```
`beforeEach`함수를 사용해서 테스트가 실행될 때마다 항상 일정한 상태에서 시작할 수 있도록 해주는게 좋을 것 같아요.
그러지 않으면 테스트가 다른 테스트들에 영향을 미칠 수 있고, 그러면 테스트가 올바르게 동작하지 않거나 유지보수하기 힘들어질 거에요.

2021-05-28 15:02 UTC, Kihyun92 commented on src/InputContainer.test.jsx
> +  it('handleClickAddTask가 호출되는지 확인하는 테스트입니다', () => {
이 테스트에 대해서 알려주는 것도 좋지만, 사용 설명서 관점에서 이 테스트를 통해 무엇을 드러내고 싶은지 생각해보셔도 좋을 것 같습니다.

예를들면 `추가 버튼을 누르면 테스크가 추가됩니다` 는 어떤가요?

2021-06-08 04:48 UTC, seong-dodo commented
안녕하세요~ 
제가 코드숨 `main` 브랜치로 PR을 올려 다시 수정하였고, 피드백도 반영하였습니다~~~

2021-08-08 07:49 UTC, merged