4주차 과제
CodeSoom/week4-assignment-1 pull request #64
Opened 2021-05-25 12:46 UTC by parkjun5

강의수강 시작하였습니다. 계속 업데이트 해나가겠습니다!

2021-05-25 14:39 UTC, Kihyun92 requested changes
강의를 보고 진행하는 것도 좋지만, 보지않고 직접 해보시는 것도 좋을 것 같아요.

배워야하는 양이 많아져서 많이 힘드시겠지만, 강의 내용을 떠올려보시면서 천천히 구현해보시면 좋을 것 같습니다!

![image](https://user-images.githubusercontent.com/35797540/119516630-e42dcd00-bdb1-11eb-84d6-d654e4972b22.png)

TDD cycle에 맞춰서 하나씩 작게 진행하더라도 테스트가 항상 통과하도록 해보세요~

당장 컴포넌트를 render 하는 것 부터 하나씩 만들어나가시면 좋아요. 그러다보면 이런 저런 함수들을 만들어야할 것이고, 추후 상태 관리가 복잡해지면 Redux 로 관리하게 될거에요.

`RED - GREEN - REACTORING` 을 짧게 가져가려면 어떻게 하면 좋을지 고민해보시면 좋을 것 같아요~

2021-05-25 14:39 UTC, Kihyun92 commented on src/App.jsx
> +      onChangeTitle={(event) => dispatch(updateTaskTitle(event.target.value))}
이 부분은 따로 핸들러 함수로 사용하는게 좋을 것 같아요~

2021-05-27 14:56 UTC, kimkhyun reviewed
전반적으로 줄바꿈 처리에 신경쓰면 좋을 것 같아요. 항상 린트를 자주 돌려주세요~

그리고 사용하지 않는 주석은 제거해주세요 😊

2021-05-29 14:35 UTC, Kihyun92 commented
@parkjun5 님, 혹시 어떻게 진행 중이신지 궁금합니다~ 진행하시는데 어려움이 있거나 의논이 필요하면 편하게 말씀해주세요 😄

2021-05-30 15:03 UTC, Kihyun92 approved these changes
이번주도 고생하셨습니다~ 과제 풀이 영상을 꼭 보시고 아샬님은 어떤 방식으로 관심사를 분리하는지 보셔도 좋을 것 같아요 :)

2021-08-08 07:49 UTC, merged