[week4-1] Refactoring To-do list using Redux
CodeSoom/week4-assignment-1 pull request #8
Opened 2020-06-25 07:25 UTC by dididy

선 PR 후 작업합니다!

2020-06-25 09:09 UTC, wholemann requested changes
안녕하세요?

redux를 설치하시고 action creator를 만드셨는데

dispatch는 사용하지 않은 이유를 알 수 있을까요?

그리고 필요한 기능에 대한 test를 미리 모두 작성하시기보단

구현하고자 하는 기능에 해당 하는 테스트 하나를 먼저 작성하고

그것에 대한 구현 코드를 작성하는 순서로 가는 걸 권장합니다.

지금은 이미 구현 코드를 알고 계셔서 가능한 상황일 뿐,

대부분의 상황은 우리가 모르는 문제를 풀어가기 때문에

작게 작게 전진하지 않으면 TDD를 하기가 매우 어렵습니다.

2020-06-25 09:11 UTC, wholemann commented on src/reducer.test.jsx
> +describe('reducer', () => {
지금은 모든 테스트를 작성해놓으셨는데

작게 테스트 하나를 만들고 그 다음 구현을 해가는 방식으로 해보세요.

앞선 구현에 따라 뒤의 테스트들이 의미 없어질 확률이 높습니다. 수정 비용이 높아질 확률이 높아요.

2020-06-25 09:19 UTC, voidmatcha commented on src/reducer.test.jsx
> +describe('reducer', () => {
놓치는 부분이 있을까 싶어 강의의 것을 그대로 사용했는데 좋지 못한 행동이었군요. 예상 테스트를 지우고 필요할 때 마다 생각하고 만들어서 테스팅 및 구현을 하도록 하겠습니다!

2020-06-25 12:33 UTC, wholemann commented on src/reducer.test.jsx
> +describe('reducer', () => {
네 진행해주세요:)

2020-06-25 23:32 UTC, wholemann reviewed
테스트 통과가 안 됐네요😥

잘해주고 계시니 이 과제는 서둘러 마무리하시고 PR 날려주세요.

곧바로 다음 과제 진행하셔도 좋습니다.

2020-06-27 10:50 UTC, dididy commented
Branches Coverage 가 100%되지 않는다는 문제가 있는데 빠르게 해결해보도록 하겠습니다. 또한 지금 테스트 코드들이 정리가 안된 느낌이라 이것도 마감 전까지 두번째 과제를 완성한다면 해결해볼게요.

2020-06-27 10:52 UTC, dididy commented on src/reducer.test.jsx
> +  context('when no actions', () => {
action이 없는 경우는 이렇게 테스트하는게 맞나요?

2020-06-27 10:54 UTC, dididy commented on src/reducer.js
> +export default function reducer(state = initialState, action) {
테스트 콘솔에서 reducer의 이 라인이 Branch 88.89%가 나오는데 이유가 뭘가요?
<img width="712" alt="Screen Shot 2020-06-27 at 3 53 51 AM" src="https://user-images.githubusercontent.com/16266103/85920578-d1b9b500-b829-11ea-9e53-94a6acc642dd.png">

2020-06-27 11:28 UTC, wholemann requested changes
comment 남긴 부분 참고하셔서 조금만 보강하시면 되겠네요ㅎㅎ

다음 PR엔 끝나는 걸 목표로ㅎㅎ

과제1도 마무리 하시고 과제2도 잘 마무리해주세요!

2020-06-27 11:28 UTC, wholemann commented on src/reducer.test.jsx
> +  context('when no actions', () => {
'with no matched action'

이 맞는 표현일 거 같군요.

2020-06-27 11:28 UTC, wholemann commented on src/reducer.js
> +export default function reducer(state = initialState, action) {
reducer에 state를 전달하지 않아서 initialState가 사용되는 케이스를 테스트 하시면 됩니다.

2020-06-28 05:42 UTC, dididy commented on src/reducer.js
> +export default function reducer(state = initialState, action) {
reducer에서 initialState라는 state의 기본 매개변수가 사용되려면 undefined로 인자를 넘기면 된다는걸 배웠습니다!

2020-06-28 05:46 UTC, dididy commented
제 생각엔 아직 부족한 부분이 많은 것 같은데 모든 test가 성공해서 push 했습니다. 

수정할 부분이 있으면 다시 push 하겠습니다!

2020-06-28 05:55 UTC, wholemann approved these changes
고생하셨어요. Merge 할게요ㅎㅎ

서둘러 과제2도 마무리 해주세요!

2020-06-28 05:56 UTC, merged