1. reducer test 작성
CodeSoom/week4-assignment-1 pull request #9
Opened 2020-06-25 08:25 UTC by min-w-park

안녕하세요, 

일단 이렇게 시작하는게 맞는지 잘 모르겠지만.. 
reducer의 테스트 부터 구현을 시작하였습니다. 
테스트를 작성 하면서 임의로 테스트를 통과시키기 위해 reducer에서 하드코딩으로 리턴결과를 주었는데,
그것 또한 test 코드 내에서 처리가 되었어야 하는 것일까요? 

이 후에는, reducer를 구현하고, actions를 정의하고 store를 구현해서 결과적으로 
App을 refactoring 하는 순서로 가면 될까요?

2020-06-25 12:25 UTC, wholemann requested changes
네 잘하셨어요. 저도 일단 테스트 작성 후 하드코딩으로 구현해서 해당 테스트가 통과하도록 만든 뒤

본격적인 구현에 들어가는 편입니다.

근데 일단 강의를 보시면 아시겠지만 갑자기 reducer 테스트부터 등장하는 건 흐름이 좀 이상하죠.

reducer가 필요한 상황이 먼저 와야 reducer 테스트가 등장할 수 있죠.

강의를 보면 완전히 TDD로 진행하진 않는데 그 이유는

일단 reducer의 정체를 알려주기 위해 reducer를 먼저 구현합니다.

반대로 실습은 강의에서 나온 테스트 코드를 구현하고 실제 코드를 구현하는 흐름으로 가면 됩니다.

테스트 또한 한번에 여러 테스트를 작성하는게 아닌 한번에 하나의 테스트만

RED GREEN REFACTOR 싸이클로 진행하면 좋겠습니다.

2020-06-25 16:38 UTC, min-w-park commented
중간 점검을 위해서 작업 한 부분 까지 푸쉬 합니다.! 
구현과 리팩토링이 하다보니 조금 섞일 때가 있어 저도 모르게 커밋 하기도 했네요. 

GREEN 에서 REFACTOR로 넘어가는 사이클에 대해 좀 더 공부해 봐야겠습니다..

2020-06-25 23:03 UTC, wholemann reviewed
잘해주고 계십니다ㅎㅎ

어서 마무리하시고 다음 과제 하시면 좋겠습니다.

2020-06-25 23:03 UTC, wholemann commented on src/App.test.jsx
> +  const TASK = '테스트';
지금 같은 경우는 따로 변수로 분리하기 보단 사용하는 곳에 직접 넣는게 가독성이 좋을 것 같아요.

2020-06-27 02:56 UTC, wholemann approved these changes
잘해주셨습니다. 이번 과제에서 익힌 걸 바탕으로

과제2를 진행해주시면 되겠습니다:)

고생하셨어요.

2020-06-27 02:56 UTC, merged